// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * MinioAccessKey defines a MinIO access key - a set of child credentials belonging to a parent MinIO user.
NOTE: Historically, this feature was called 'Service Accounts'.
https://docs.min.io/community/minio-object-store/administration/identity-access-management/minio-user-management.html#access-keys
 *
 * @schema MinioAccessKey
 */
export class MinioAccessKey extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioAccessKey"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioAccessKey',
  }

  /**
   * Renders a Kubernetes manifest for "MinioAccessKey".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioAccessKeyProps): any {
    return {
      ...MinioAccessKey.GVK,
      ...toJson_MinioAccessKeyProps(props),
    };
  }

  /**
   * Defines a "MinioAccessKey" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioAccessKeyProps) {
    super(scope, id, {
      ...MinioAccessKey.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioAccessKey.GVK,
      ...toJson_MinioAccessKeyProps(resolved),
    };
  }
}

/**
 * MinioAccessKey defines a MinIO access key - a set of child credentials belonging to a parent MinIO user.
 * NOTE: Historically, this feature was called 'Service Accounts'.
 * https://docs.min.io/community/minio-object-store/administration/identity-access-management/minio-user-management.html#access-keys
 *
 * @schema MinioAccessKey
 */
export interface MinioAccessKeyProps {
  /**
   * @schema MinioAccessKey#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioAccessKeySpec defines the desired state of MinioAccessKey
   *
   * @schema MinioAccessKey#spec
   */
  readonly spec: MinioAccessKeySpec;
}

/**
 * Converts an object of type 'MinioAccessKeyProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeyProps(obj: MinioAccessKeyProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioAccessKeySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioAccessKeySpec defines the desired state of MinioAccessKey
 *
 * @schema MinioAccessKeySpec
 */
export interface MinioAccessKeySpec {
  /**
   * @schema MinioAccessKeySpec#accessKey
   */
  readonly accessKey?: string;

  /**
   * ResourceKeyRef defines a reference to a key of another kubernetes resource
   *
   * @schema MinioAccessKeySpec#accessKeyRef
   */
  readonly accessKeyRef?: MinioAccessKeySpecAccessKeyRef;

  /**
   * @schema MinioAccessKeySpec#description
   */
  readonly description?: string;

  /**
   * @schema MinioAccessKeySpec#expiration
   */
  readonly expiration?: Date;

  /**
   * @schema MinioAccessKeySpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * @schema MinioAccessKeySpec#name
   */
  readonly name: string;

  /**
   * MinioAccessKeyPolicy represents a policy attached to a MinioAccessKey
   *
   * @schema MinioAccessKeySpec#policy
   */
  readonly policy?: MinioAccessKeySpecPolicy;

  /**
   * ResourceKeyRef defines a reference to a key of another kubernetes resource
   *
   * @schema MinioAccessKeySpec#secretKeyRef
   */
  readonly secretKeyRef?: MinioAccessKeySpecSecretKeyRef;

  /**
   * @schema MinioAccessKeySpec#secretName
   */
  readonly secretName: string;

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioAccessKeySpec#tenantRef
   */
  readonly tenantRef: MinioAccessKeySpecTenantRef;

  /**
   * MinioAccessKeyIdentity represents an identity attached to a MinioAccessKey
   *
   * @schema MinioAccessKeySpec#user
   */
  readonly user: MinioAccessKeySpecUser;
}

/**
 * Converts an object of type 'MinioAccessKeySpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpec(obj: MinioAccessKeySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKey': obj.accessKey,
    'accessKeyRef': toJson_MinioAccessKeySpecAccessKeyRef(obj.accessKeyRef),
    'description': obj.description,
    'expiration': obj.expiration?.toISOString(),
    'migrate': obj.migrate,
    'name': obj.name,
    'policy': toJson_MinioAccessKeySpecPolicy(obj.policy),
    'secretKeyRef': toJson_MinioAccessKeySpecSecretKeyRef(obj.secretKeyRef),
    'secretName': obj.secretName,
    'tenantRef': toJson_MinioAccessKeySpecTenantRef(obj.tenantRef),
    'user': toJson_MinioAccessKeySpecUser(obj.user),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceKeyRef defines a reference to a key of another kubernetes resource
 *
 * @schema MinioAccessKeySpecAccessKeyRef
 */
export interface MinioAccessKeySpecAccessKeyRef {
  /**
   * @schema MinioAccessKeySpecAccessKeyRef#key
   */
  readonly key: string;

  /**
   * @schema MinioAccessKeySpecAccessKeyRef#name
   */
  readonly name: string;

  /**
   * @schema MinioAccessKeySpecAccessKeyRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioAccessKeySpecAccessKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpecAccessKeyRef(obj: MinioAccessKeySpecAccessKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioAccessKeyPolicy represents a policy attached to a MinioAccessKey
 *
 * @schema MinioAccessKeySpecPolicy
 */
export interface MinioAccessKeySpecPolicy {
  /**
   * @schema MinioAccessKeySpecPolicy#statement
   */
  readonly statement?: MinioAccessKeySpecPolicyStatement[];

  /**
   * @schema MinioAccessKeySpecPolicy#version
   */
  readonly version?: string;
}

/**
 * Converts an object of type 'MinioAccessKeySpecPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpecPolicy(obj: MinioAccessKeySpecPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'statement': obj.statement?.map(y => toJson_MinioAccessKeySpecPolicyStatement(y)),
    'version': obj.version,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceKeyRef defines a reference to a key of another kubernetes resource
 *
 * @schema MinioAccessKeySpecSecretKeyRef
 */
export interface MinioAccessKeySpecSecretKeyRef {
  /**
   * @schema MinioAccessKeySpecSecretKeyRef#key
   */
  readonly key: string;

  /**
   * @schema MinioAccessKeySpecSecretKeyRef#name
   */
  readonly name: string;

  /**
   * @schema MinioAccessKeySpecSecretKeyRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioAccessKeySpecSecretKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpecSecretKeyRef(obj: MinioAccessKeySpecSecretKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioAccessKeySpecTenantRef
 */
export interface MinioAccessKeySpecTenantRef {
  /**
   * @schema MinioAccessKeySpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioAccessKeySpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioAccessKeySpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpecTenantRef(obj: MinioAccessKeySpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioAccessKeyIdentity represents an identity attached to a MinioAccessKey
 *
 * @schema MinioAccessKeySpecUser
 */
export interface MinioAccessKeySpecUser {
  /**
   * @schema MinioAccessKeySpecUser#builtin
   */
  readonly builtin?: string;

  /**
   * @schema MinioAccessKeySpecUser#ldap
   */
  readonly ldap?: string;
}

/**
 * Converts an object of type 'MinioAccessKeySpecUser' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpecUser(obj: MinioAccessKeySpecUser | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'builtin': obj.builtin,
    'ldap': obj.ldap,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioPolicyStatement defines a single statement within a MinioPolicy
 *
 * @schema MinioAccessKeySpecPolicyStatement
 */
export interface MinioAccessKeySpecPolicyStatement {
  /**
   * @schema MinioAccessKeySpecPolicyStatement#action
   */
  readonly action: string[];

  /**
   * @schema MinioAccessKeySpecPolicyStatement#effect
   */
  readonly effect: string;

  /**
   * @schema MinioAccessKeySpecPolicyStatement#resource
   */
  readonly resource: string[];
}

/**
 * Converts an object of type 'MinioAccessKeySpecPolicyStatement' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioAccessKeySpecPolicyStatement(obj: MinioAccessKeySpecPolicyStatement | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'action': obj.action?.map(y => y),
    'effect': obj.effect,
    'resource': obj.resource?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * MinioBucket defines a MinIO tenant bucket.
 *
 * @schema MinioBucket
 */
export class MinioBucket extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioBucket"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioBucket',
  }

  /**
   * Renders a Kubernetes manifest for "MinioBucket".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioBucketProps): any {
    return {
      ...MinioBucket.GVK,
      ...toJson_MinioBucketProps(props),
    };
  }

  /**
   * Defines a "MinioBucket" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioBucketProps) {
    super(scope, id, {
      ...MinioBucket.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioBucket.GVK,
      ...toJson_MinioBucketProps(resolved),
    };
  }
}

/**
 * MinioBucket defines a MinIO tenant bucket.
 *
 * @schema MinioBucket
 */
export interface MinioBucketProps {
  /**
   * @schema MinioBucket#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioBucketSpec defines the desired state of MinioBucket
   *
   * @schema MinioBucket#spec
   */
  readonly spec: MinioBucketSpec;
}

/**
 * Converts an object of type 'MinioBucketProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketProps(obj: MinioBucketProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioBucketSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketSpec defines the desired state of MinioBucket
 *
 * @schema MinioBucketSpec
 */
export interface MinioBucketSpec {
  /**
   * @schema MinioBucketSpec#deletionPolicy
   */
  readonly deletionPolicy: string;

  /**
   * MinioBucketLifecycleConfiguration is effectively a copy of [lifecycle.Configuration].
   *
   * @schema MinioBucketSpec#lifecycle
   */
  readonly lifecycle?: MinioBucketSpecLifecycle;

  /**
   * @schema MinioBucketSpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * @schema MinioBucketSpec#name
   */
  readonly name: string;

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioBucketSpec#tenantRef
   */
  readonly tenantRef: MinioBucketSpecTenantRef;

  /**
   * MinioBucketVersioningConfiguration is effectively a copy of [minioclient.BucketVersioningConfiguration].
   *
   * @schema MinioBucketSpec#versioning
   */
  readonly versioning?: MinioBucketSpecVersioning;
}

/**
 * Converts an object of type 'MinioBucketSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpec(obj: MinioBucketSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'deletionPolicy': obj.deletionPolicy,
    'lifecycle': toJson_MinioBucketSpecLifecycle(obj.lifecycle),
    'migrate': obj.migrate,
    'name': obj.name,
    'tenantRef': toJson_MinioBucketSpecTenantRef(obj.tenantRef),
    'versioning': toJson_MinioBucketSpecVersioning(obj.versioning),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleConfiguration is effectively a copy of [lifecycle.Configuration].
 *
 * @schema MinioBucketSpecLifecycle
 */
export interface MinioBucketSpecLifecycle {
  /**
   * @schema MinioBucketSpecLifecycle#Rules
   */
  readonly rules: MinioBucketSpecLifecycleRules[];
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycle' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycle(obj: MinioBucketSpecLifecycle | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Rules': obj.rules?.map(y => toJson_MinioBucketSpecLifecycleRules(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioBucketSpecTenantRef
 */
export interface MinioBucketSpecTenantRef {
  /**
   * @schema MinioBucketSpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioBucketSpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioBucketSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecTenantRef(obj: MinioBucketSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketVersioningConfiguration is effectively a copy of [minioclient.BucketVersioningConfiguration].
 *
 * @schema MinioBucketSpecVersioning
 */
export interface MinioBucketSpecVersioning {
  /**
   * @schema MinioBucketSpecVersioning#ExcludeFolders
   */
  readonly excludeFolders?: boolean;

  /**
   * @schema MinioBucketSpecVersioning#ExcludedPrefixes
   */
  readonly excludedPrefixes?: MinioBucketSpecVersioningExcludedPrefixes[];

  /**
   * @schema MinioBucketSpecVersioning#MfaDelete
   */
  readonly mfaDelete?: string;

  /**
   * @schema MinioBucketSpecVersioning#Status
   */
  readonly status: string;
}

/**
 * Converts an object of type 'MinioBucketSpecVersioning' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecVersioning(obj: MinioBucketSpecVersioning | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ExcludeFolders': obj.excludeFolders,
    'ExcludedPrefixes': obj.excludedPrefixes?.map(y => toJson_MinioBucketSpecVersioningExcludedPrefixes(y)),
    'MfaDelete': obj.mfaDelete,
    'Status': obj.status,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleRule is effectively a copy of [lifecycle.Rule].
 *
 * @schema MinioBucketSpecLifecycleRules
 */
export interface MinioBucketSpecLifecycleRules {
  /**
   * MinioBucketLifecycleAbortIncompleteMultipartUpload is effectively a copy of [lifecycle.AbortIncompleteMultipartUpload].
   *
   * @schema MinioBucketSpecLifecycleRules#AbortIncompleteMultipartUpload
   */
  readonly abortIncompleteMultipartUpload?: MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload;

  /**
   * MinioBucketLifecycleDelMarkerExpiration is effectively a copy of [lifecycle.DelMarkerExpiration].
   *
   * @schema MinioBucketSpecLifecycleRules#DelMarkerExpiration
   */
  readonly delMarkerExpiration?: MinioBucketSpecLifecycleRulesDelMarkerExpiration;

  /**
   * MinioBucketLifecycleExpiration is effectively a copy of [lifecycle.Expiration].
   *
   * @schema MinioBucketSpecLifecycleRules#Expiration
   */
  readonly expiration?: MinioBucketSpecLifecycleRulesExpiration;

  /**
   * MinioBucketLifecycleFilter is effectively a copy of [lifecycle.Filter].
   *
   * @schema MinioBucketSpecLifecycleRules#Filter
   */
  readonly filter?: MinioBucketSpecLifecycleRulesFilter;

  /**
   * @schema MinioBucketSpecLifecycleRules#ID
   */
  readonly id: string;

  /**
   * MinioBucketLifecycleNoncurrentVersionExpiration is effectively a copy of [lifecycle.Expiration].
   *
   * @schema MinioBucketSpecLifecycleRules#NoncurrentVersionExpiration
   */
  readonly noncurrentVersionExpiration?: MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration;

  /**
   * MinioBucketLifecycleNoncurrentVersionTransition is effectively a copy of [lifecycle.NoncurrentVersionTransition].
   *
   * @schema MinioBucketSpecLifecycleRules#NoncurrentVersionTransition
   */
  readonly noncurrentVersionTransition?: MinioBucketSpecLifecycleRulesNoncurrentVersionTransition;

  /**
   * @schema MinioBucketSpecLifecycleRules#Prefix
   */
  readonly prefix?: string;

  /**
   * @schema MinioBucketSpecLifecycleRules#Status
   */
  readonly status: string;

  /**
   * MinioBucketLifecycleTransition is effectively a copy of [lifecycle.Transition].
   *
   * @schema MinioBucketSpecLifecycleRules#Transition
   */
  readonly transition?: MinioBucketSpecLifecycleRulesTransition;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRules' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRules(obj: MinioBucketSpecLifecycleRules | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'AbortIncompleteMultipartUpload': toJson_MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload(obj.abortIncompleteMultipartUpload),
    'DelMarkerExpiration': toJson_MinioBucketSpecLifecycleRulesDelMarkerExpiration(obj.delMarkerExpiration),
    'Expiration': toJson_MinioBucketSpecLifecycleRulesExpiration(obj.expiration),
    'Filter': toJson_MinioBucketSpecLifecycleRulesFilter(obj.filter),
    'ID': obj.id,
    'NoncurrentVersionExpiration': toJson_MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration(obj.noncurrentVersionExpiration),
    'NoncurrentVersionTransition': toJson_MinioBucketSpecLifecycleRulesNoncurrentVersionTransition(obj.noncurrentVersionTransition),
    'Prefix': obj.prefix,
    'Status': obj.status,
    'Transition': toJson_MinioBucketSpecLifecycleRulesTransition(obj.transition),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketVersioningExcludedPrefix is effectively a copy of [minioclient.ExcludedPrefix].
 *
 * @schema MinioBucketSpecVersioningExcludedPrefixes
 */
export interface MinioBucketSpecVersioningExcludedPrefixes {
  /**
   * @schema MinioBucketSpecVersioningExcludedPrefixes#Prefix
   */
  readonly prefix: string;
}

/**
 * Converts an object of type 'MinioBucketSpecVersioningExcludedPrefixes' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecVersioningExcludedPrefixes(obj: MinioBucketSpecVersioningExcludedPrefixes | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Prefix': obj.prefix,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleAbortIncompleteMultipartUpload is effectively a copy of [lifecycle.AbortIncompleteMultipartUpload].
 *
 * @schema MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload
 */
export interface MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload {
  /**
   * @schema MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload#DaysAfterInitiation
   */
  readonly daysAfterInitiation?: number;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload(obj: MinioBucketSpecLifecycleRulesAbortIncompleteMultipartUpload | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'DaysAfterInitiation': obj.daysAfterInitiation,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleDelMarkerExpiration is effectively a copy of [lifecycle.DelMarkerExpiration].
 *
 * @schema MinioBucketSpecLifecycleRulesDelMarkerExpiration
 */
export interface MinioBucketSpecLifecycleRulesDelMarkerExpiration {
  /**
   * @schema MinioBucketSpecLifecycleRulesDelMarkerExpiration#Days
   */
  readonly days?: number;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesDelMarkerExpiration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesDelMarkerExpiration(obj: MinioBucketSpecLifecycleRulesDelMarkerExpiration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Days': obj.days,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleExpiration is effectively a copy of [lifecycle.Expiration].
 *
 * @schema MinioBucketSpecLifecycleRulesExpiration
 */
export interface MinioBucketSpecLifecycleRulesExpiration {
  /**
   * @schema MinioBucketSpecLifecycleRulesExpiration#Date
   */
  readonly date?: Date;

  /**
   * @schema MinioBucketSpecLifecycleRulesExpiration#Days
   */
  readonly days?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesExpiration#ExpiredObjectAllVersions
   */
  readonly expiredObjectAllVersions?: boolean;

  /**
   * @schema MinioBucketSpecLifecycleRulesExpiration#ExpiredObjectDeleteMarker
   */
  readonly expiredObjectDeleteMarker?: boolean;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesExpiration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesExpiration(obj: MinioBucketSpecLifecycleRulesExpiration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Date': obj.date?.toISOString(),
    'Days': obj.days,
    'ExpiredObjectAllVersions': obj.expiredObjectAllVersions,
    'ExpiredObjectDeleteMarker': obj.expiredObjectDeleteMarker,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleFilter is effectively a copy of [lifecycle.Filter].
 *
 * @schema MinioBucketSpecLifecycleRulesFilter
 */
export interface MinioBucketSpecLifecycleRulesFilter {
  /**
   * MinioBucketLifecycleAnd is effectively a copy of [lifecycle.And].
   *
   * @schema MinioBucketSpecLifecycleRulesFilter#And
   */
  readonly and?: MinioBucketSpecLifecycleRulesFilterAnd;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilter#ObjectSizeGreaterThan
   */
  readonly objectSizeGreaterThan?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilter#ObjectSizeLessThan
   */
  readonly objectSizeLessThan?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilter#Prefix
   */
  readonly prefix?: string;

  /**
   * MinioBucketLifecycleTag is effectively a copy of [lifecycle.Tag].
   *
   * @schema MinioBucketSpecLifecycleRulesFilter#Tag
   */
  readonly tag?: MinioBucketSpecLifecycleRulesFilterTag;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesFilter' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesFilter(obj: MinioBucketSpecLifecycleRulesFilter | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'And': toJson_MinioBucketSpecLifecycleRulesFilterAnd(obj.and),
    'ObjectSizeGreaterThan': obj.objectSizeGreaterThan,
    'ObjectSizeLessThan': obj.objectSizeLessThan,
    'Prefix': obj.prefix,
    'Tag': toJson_MinioBucketSpecLifecycleRulesFilterTag(obj.tag),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleNoncurrentVersionExpiration is effectively a copy of [lifecycle.Expiration].
 *
 * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration
 */
export interface MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration {
  /**
   * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration#NewerNoncurrentVersions
   */
  readonly newerNoncurrentVersions?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration#NoncurrentDays
   */
  readonly noncurrentDays?: number;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration(obj: MinioBucketSpecLifecycleRulesNoncurrentVersionExpiration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'NewerNoncurrentVersions': obj.newerNoncurrentVersions,
    'NoncurrentDays': obj.noncurrentDays,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleNoncurrentVersionTransition is effectively a copy of [lifecycle.NoncurrentVersionTransition].
 *
 * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionTransition
 */
export interface MinioBucketSpecLifecycleRulesNoncurrentVersionTransition {
  /**
   * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionTransition#NewerNoncurrentVersions
   */
  readonly newerNoncurrentVersions?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionTransition#NoncurrentDays
   */
  readonly noncurrentDays: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesNoncurrentVersionTransition#StorageClass
   */
  readonly storageClass?: string;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesNoncurrentVersionTransition' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesNoncurrentVersionTransition(obj: MinioBucketSpecLifecycleRulesNoncurrentVersionTransition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'NewerNoncurrentVersions': obj.newerNoncurrentVersions,
    'NoncurrentDays': obj.noncurrentDays,
    'StorageClass': obj.storageClass,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleTransition is effectively a copy of [lifecycle.Transition].
 *
 * @schema MinioBucketSpecLifecycleRulesTransition
 */
export interface MinioBucketSpecLifecycleRulesTransition {
  /**
   * @schema MinioBucketSpecLifecycleRulesTransition#Date
   */
  readonly date?: Date;

  /**
   * @schema MinioBucketSpecLifecycleRulesTransition#Days
   */
  readonly days: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesTransition#StorageClass
   */
  readonly storageClass?: string;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesTransition' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesTransition(obj: MinioBucketSpecLifecycleRulesTransition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Date': obj.date?.toISOString(),
    'Days': obj.days,
    'StorageClass': obj.storageClass,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleAnd is effectively a copy of [lifecycle.And].
 *
 * @schema MinioBucketSpecLifecycleRulesFilterAnd
 */
export interface MinioBucketSpecLifecycleRulesFilterAnd {
  /**
   * @schema MinioBucketSpecLifecycleRulesFilterAnd#ObjectSizeGreaterThan
   */
  readonly objectSizeGreaterThan?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilterAnd#ObjectSizeLessThan
   */
  readonly objectSizeLessThan?: number;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilterAnd#Prefix
   */
  readonly prefix?: string;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilterAnd#Tags
   */
  readonly tags?: MinioBucketSpecLifecycleRulesFilterAndTags[];
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesFilterAnd' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesFilterAnd(obj: MinioBucketSpecLifecycleRulesFilterAnd | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ObjectSizeGreaterThan': obj.objectSizeGreaterThan,
    'ObjectSizeLessThan': obj.objectSizeLessThan,
    'Prefix': obj.prefix,
    'Tags': obj.tags?.map(y => toJson_MinioBucketSpecLifecycleRulesFilterAndTags(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleTag is effectively a copy of [lifecycle.Tag].
 *
 * @schema MinioBucketSpecLifecycleRulesFilterTag
 */
export interface MinioBucketSpecLifecycleRulesFilterTag {
  /**
   * @schema MinioBucketSpecLifecycleRulesFilterTag#Key
   */
  readonly key?: string;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilterTag#Value
   */
  readonly value?: string;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesFilterTag' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesFilterTag(obj: MinioBucketSpecLifecycleRulesFilterTag | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Key': obj.key,
    'Value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioBucketLifecycleTag is effectively a copy of [lifecycle.Tag].
 *
 * @schema MinioBucketSpecLifecycleRulesFilterAndTags
 */
export interface MinioBucketSpecLifecycleRulesFilterAndTags {
  /**
   * @schema MinioBucketSpecLifecycleRulesFilterAndTags#Key
   */
  readonly key?: string;

  /**
   * @schema MinioBucketSpecLifecycleRulesFilterAndTags#Value
   */
  readonly value?: string;
}

/**
 * Converts an object of type 'MinioBucketSpecLifecycleRulesFilterAndTags' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioBucketSpecLifecycleRulesFilterAndTags(obj: MinioBucketSpecLifecycleRulesFilterAndTags | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Key': obj.key,
    'Value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * MinioGroup defines a MinIO builtin group identity.
 *
 * @schema MinioGroup
 */
export class MinioGroup extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioGroup"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioGroup',
  }

  /**
   * Renders a Kubernetes manifest for "MinioGroup".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioGroupProps): any {
    return {
      ...MinioGroup.GVK,
      ...toJson_MinioGroupProps(props),
    };
  }

  /**
   * Defines a "MinioGroup" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioGroupProps) {
    super(scope, id, {
      ...MinioGroup.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioGroup.GVK,
      ...toJson_MinioGroupProps(resolved),
    };
  }
}

/**
 * MinioGroup defines a MinIO builtin group identity.
 *
 * @schema MinioGroup
 */
export interface MinioGroupProps {
  /**
   * @schema MinioGroup#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioGroupSpec defines the desired state of MinioGroup
   *
   * @schema MinioGroup#spec
   */
  readonly spec: MinioGroupSpec;
}

/**
 * Converts an object of type 'MinioGroupProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioGroupProps(obj: MinioGroupProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioGroupSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioGroupSpec defines the desired state of MinioGroup
 *
 * @schema MinioGroupSpec
 */
export interface MinioGroupSpec {
  /**
   * @schema MinioGroupSpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * @schema MinioGroupSpec#name
   */
  readonly name: string;

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioGroupSpec#tenantRef
   */
  readonly tenantRef: MinioGroupSpecTenantRef;
}

/**
 * Converts an object of type 'MinioGroupSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioGroupSpec(obj: MinioGroupSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'migrate': obj.migrate,
    'name': obj.name,
    'tenantRef': toJson_MinioGroupSpecTenantRef(obj.tenantRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioGroupSpecTenantRef
 */
export interface MinioGroupSpecTenantRef {
  /**
   * @schema MinioGroupSpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioGroupSpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioGroupSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioGroupSpecTenantRef(obj: MinioGroupSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * MinioGroupBinding attaches a MinIO builtin user identity to a MinIO builtin group identity
 *
 * @schema MinioGroupBinding
 */
export class MinioGroupBinding extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioGroupBinding"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioGroupBinding',
  }

  /**
   * Renders a Kubernetes manifest for "MinioGroupBinding".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioGroupBindingProps): any {
    return {
      ...MinioGroupBinding.GVK,
      ...toJson_MinioGroupBindingProps(props),
    };
  }

  /**
   * Defines a "MinioGroupBinding" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioGroupBindingProps) {
    super(scope, id, {
      ...MinioGroupBinding.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioGroupBinding.GVK,
      ...toJson_MinioGroupBindingProps(resolved),
    };
  }
}

/**
 * MinioGroupBinding attaches a MinIO builtin user identity to a MinIO builtin group identity
 *
 * @schema MinioGroupBinding
 */
export interface MinioGroupBindingProps {
  /**
   * @schema MinioGroupBinding#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioGroupBindingSpec defines the desired state of MinioGroupBinding
   *
   * @schema MinioGroupBinding#spec
   */
  readonly spec: MinioGroupBindingSpec;
}

/**
 * Converts an object of type 'MinioGroupBindingProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioGroupBindingProps(obj: MinioGroupBindingProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioGroupBindingSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioGroupBindingSpec defines the desired state of MinioGroupBinding
 *
 * @schema MinioGroupBindingSpec
 */
export interface MinioGroupBindingSpec {
  /**
   * @schema MinioGroupBindingSpec#group
   */
  readonly group: string;

  /**
   * @schema MinioGroupBindingSpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioGroupBindingSpec#tenantRef
   */
  readonly tenantRef?: MinioGroupBindingSpecTenantRef;

  /**
   * @schema MinioGroupBindingSpec#user
   */
  readonly user: string;
}

/**
 * Converts an object of type 'MinioGroupBindingSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioGroupBindingSpec(obj: MinioGroupBindingSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'group': obj.group,
    'migrate': obj.migrate,
    'tenantRef': toJson_MinioGroupBindingSpecTenantRef(obj.tenantRef),
    'user': obj.user,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioGroupBindingSpecTenantRef
 */
export interface MinioGroupBindingSpecTenantRef {
  /**
   * @schema MinioGroupBindingSpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioGroupBindingSpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioGroupBindingSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioGroupBindingSpecTenantRef(obj: MinioGroupBindingSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * MinioPolicy defines a MinIO tenant policy
 *
 * @schema MinioPolicy
 */
export class MinioPolicy extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioPolicy"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioPolicy',
  }

  /**
   * Renders a Kubernetes manifest for "MinioPolicy".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioPolicyProps): any {
    return {
      ...MinioPolicy.GVK,
      ...toJson_MinioPolicyProps(props),
    };
  }

  /**
   * Defines a "MinioPolicy" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioPolicyProps) {
    super(scope, id, {
      ...MinioPolicy.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioPolicy.GVK,
      ...toJson_MinioPolicyProps(resolved),
    };
  }
}

/**
 * MinioPolicy defines a MinIO tenant policy
 *
 * @schema MinioPolicy
 */
export interface MinioPolicyProps {
  /**
   * @schema MinioPolicy#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioPolicySpec defines the desired state of MinioPolicy
   *
   * @schema MinioPolicy#spec
   */
  readonly spec: MinioPolicySpec;
}

/**
 * Converts an object of type 'MinioPolicyProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicyProps(obj: MinioPolicyProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioPolicySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioPolicySpec defines the desired state of MinioPolicy
 *
 * @schema MinioPolicySpec
 */
export interface MinioPolicySpec {
  /**
   * @schema MinioPolicySpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * @schema MinioPolicySpec#name
   */
  readonly name: string;

  /**
   * @schema MinioPolicySpec#statement
   */
  readonly statement: MinioPolicySpecStatement[];

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioPolicySpec#tenantRef
   */
  readonly tenantRef: MinioPolicySpecTenantRef;

  /**
   * @schema MinioPolicySpec#version
   */
  readonly version: string;
}

/**
 * Converts an object of type 'MinioPolicySpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicySpec(obj: MinioPolicySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'migrate': obj.migrate,
    'name': obj.name,
    'statement': obj.statement?.map(y => toJson_MinioPolicySpecStatement(y)),
    'tenantRef': toJson_MinioPolicySpecTenantRef(obj.tenantRef),
    'version': obj.version,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioPolicyStatement defines a single statement within a MinioPolicy
 *
 * @schema MinioPolicySpecStatement
 */
export interface MinioPolicySpecStatement {
  /**
   * @schema MinioPolicySpecStatement#action
   */
  readonly action: string[];

  /**
   * @schema MinioPolicySpecStatement#effect
   */
  readonly effect: string;

  /**
   * @schema MinioPolicySpecStatement#resource
   */
  readonly resource: string[];
}

/**
 * Converts an object of type 'MinioPolicySpecStatement' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicySpecStatement(obj: MinioPolicySpecStatement | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'action': obj.action?.map(y => y),
    'effect': obj.effect,
    'resource': obj.resource?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioPolicySpecTenantRef
 */
export interface MinioPolicySpecTenantRef {
  /**
   * @schema MinioPolicySpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioPolicySpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioPolicySpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicySpecTenantRef(obj: MinioPolicySpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * MinioPolicyBinding attaches a MinIO identity to a MinIO policy
 *
 * @schema MinioPolicyBinding
 */
export class MinioPolicyBinding extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioPolicyBinding"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioPolicyBinding',
  }

  /**
   * Renders a Kubernetes manifest for "MinioPolicyBinding".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioPolicyBindingProps): any {
    return {
      ...MinioPolicyBinding.GVK,
      ...toJson_MinioPolicyBindingProps(props),
    };
  }

  /**
   * Defines a "MinioPolicyBinding" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioPolicyBindingProps) {
    super(scope, id, {
      ...MinioPolicyBinding.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioPolicyBinding.GVK,
      ...toJson_MinioPolicyBindingProps(resolved),
    };
  }
}

/**
 * MinioPolicyBinding attaches a MinIO identity to a MinIO policy
 *
 * @schema MinioPolicyBinding
 */
export interface MinioPolicyBindingProps {
  /**
   * @schema MinioPolicyBinding#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioPolicyBindingSpec defines the desired state of MinioPolicyBinding
   *
   * @schema MinioPolicyBinding#spec
   */
  readonly spec: MinioPolicyBindingSpec;
}

/**
 * Converts an object of type 'MinioPolicyBindingProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicyBindingProps(obj: MinioPolicyBindingProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioPolicyBindingSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioPolicyBindingSpec defines the desired state of MinioPolicyBinding
 *
 * @schema MinioPolicyBindingSpec
 */
export interface MinioPolicyBindingSpec {
  /**
   * @schema MinioPolicyBindingSpec#group
   */
  readonly group?: MinioPolicyBindingSpecGroup;

  /**
   * @schema MinioPolicyBindingSpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * @schema MinioPolicyBindingSpec#policy
   */
  readonly policy: string;

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioPolicyBindingSpec#tenantRef
   */
  readonly tenantRef: MinioPolicyBindingSpecTenantRef;

  /**
   * @schema MinioPolicyBindingSpec#user
   */
  readonly user?: MinioPolicyBindingSpecUser;
}

/**
 * Converts an object of type 'MinioPolicyBindingSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicyBindingSpec(obj: MinioPolicyBindingSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'group': toJson_MinioPolicyBindingSpecGroup(obj.group),
    'migrate': obj.migrate,
    'policy': obj.policy,
    'tenantRef': toJson_MinioPolicyBindingSpecTenantRef(obj.tenantRef),
    'user': toJson_MinioPolicyBindingSpecUser(obj.user),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema MinioPolicyBindingSpecGroup
 */
export interface MinioPolicyBindingSpecGroup {
  /**
   * @schema MinioPolicyBindingSpecGroup#builtin
   */
  readonly builtin?: string;

  /**
   * @schema MinioPolicyBindingSpecGroup#ldap
   */
  readonly ldap?: string;
}

/**
 * Converts an object of type 'MinioPolicyBindingSpecGroup' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicyBindingSpecGroup(obj: MinioPolicyBindingSpecGroup | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'builtin': obj.builtin,
    'ldap': obj.ldap,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioPolicyBindingSpecTenantRef
 */
export interface MinioPolicyBindingSpecTenantRef {
  /**
   * @schema MinioPolicyBindingSpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioPolicyBindingSpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioPolicyBindingSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicyBindingSpecTenantRef(obj: MinioPolicyBindingSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema MinioPolicyBindingSpecUser
 */
export interface MinioPolicyBindingSpecUser {
  /**
   * @schema MinioPolicyBindingSpecUser#builtin
   */
  readonly builtin?: string;

  /**
   * @schema MinioPolicyBindingSpecUser#ldap
   */
  readonly ldap?: string;
}

/**
 * Converts an object of type 'MinioPolicyBindingSpecUser' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioPolicyBindingSpecUser(obj: MinioPolicyBindingSpecUser | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'builtin': obj.builtin,
    'ldap': obj.ldap,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * MinioUser defines a MinIO builtin user identity.
 *
 * @schema MinioUser
 */
export class MinioUser extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioUser"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioUser',
  }

  /**
   * Renders a Kubernetes manifest for "MinioUser".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioUserProps): any {
    return {
      ...MinioUser.GVK,
      ...toJson_MinioUserProps(props),
    };
  }

  /**
   * Defines a "MinioUser" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioUserProps) {
    super(scope, id, {
      ...MinioUser.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioUser.GVK,
      ...toJson_MinioUserProps(resolved),
    };
  }
}

/**
 * MinioUser defines a MinIO builtin user identity.
 *
 * @schema MinioUser
 */
export interface MinioUserProps {
  /**
   * @schema MinioUser#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * MinioUserSpec defines the desired state of MinioUser
   *
   * @schema MinioUser#spec
   */
  readonly spec: MinioUserSpec;
}

/**
 * Converts an object of type 'MinioUserProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioUserProps(obj: MinioUserProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioUserSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * MinioUserSpec defines the desired state of MinioUser
 *
 * @schema MinioUserSpec
 */
export interface MinioUserSpec {
  /**
   * @schema MinioUserSpec#accessKey
   */
  readonly accessKey?: string;

  /**
   * ResourceKeyRef defines a reference to a key of another kubernetes resource
   *
   * @schema MinioUserSpec#accessKeyRef
   */
  readonly accessKeyRef?: MinioUserSpecAccessKeyRef;

  /**
   * @schema MinioUserSpec#migrate
   */
  readonly migrate?: boolean;

  /**
   * ResourceKeyRef defines a reference to a key of another kubernetes resource
   *
   * @schema MinioUserSpec#secretKeyRef
   */
  readonly secretKeyRef: MinioUserSpecSecretKeyRef;

  /**
   * ResourceRef defines a reference to another kubernetes resource
   *
   * @schema MinioUserSpec#tenantRef
   */
  readonly tenantRef: MinioUserSpecTenantRef;
}

/**
 * Converts an object of type 'MinioUserSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioUserSpec(obj: MinioUserSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKey': obj.accessKey,
    'accessKeyRef': toJson_MinioUserSpecAccessKeyRef(obj.accessKeyRef),
    'migrate': obj.migrate,
    'secretKeyRef': toJson_MinioUserSpecSecretKeyRef(obj.secretKeyRef),
    'tenantRef': toJson_MinioUserSpecTenantRef(obj.tenantRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceKeyRef defines a reference to a key of another kubernetes resource
 *
 * @schema MinioUserSpecAccessKeyRef
 */
export interface MinioUserSpecAccessKeyRef {
  /**
   * @schema MinioUserSpecAccessKeyRef#key
   */
  readonly key: string;

  /**
   * @schema MinioUserSpecAccessKeyRef#name
   */
  readonly name: string;

  /**
   * @schema MinioUserSpecAccessKeyRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioUserSpecAccessKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioUserSpecAccessKeyRef(obj: MinioUserSpecAccessKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceKeyRef defines a reference to a key of another kubernetes resource
 *
 * @schema MinioUserSpecSecretKeyRef
 */
export interface MinioUserSpecSecretKeyRef {
  /**
   * @schema MinioUserSpecSecretKeyRef#key
   */
  readonly key: string;

  /**
   * @schema MinioUserSpecSecretKeyRef#name
   */
  readonly name: string;

  /**
   * @schema MinioUserSpecSecretKeyRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioUserSpecSecretKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioUserSpecSecretKeyRef(obj: MinioUserSpecSecretKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ResourceRef defines a reference to another kubernetes resource
 *
 * @schema MinioUserSpecTenantRef
 */
export interface MinioUserSpecTenantRef {
  /**
   * @schema MinioUserSpecTenantRef#name
   */
  readonly name: string;

  /**
   * @schema MinioUserSpecTenantRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'MinioUserSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_MinioUserSpecTenantRef(obj: MinioUserSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

