// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema MinioBucket
 */
export class MinioBucket extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioBucket"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioBucket',
  }

  /**
   * Renders a Kubernetes manifest for "MinioBucket".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioBucketProps = {}): any {
    return {
      ...MinioBucket.GVK,
      ...toJson_MinioBucketProps(props),
    };
  }

  /**
   * Defines a "MinioBucket" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioBucketProps = {}) {
    super(scope, id, {
      ...MinioBucket.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioBucket.GVK,
      ...toJson_MinioBucketProps(resolved),
    };
  }
}

/**
 * @schema MinioBucket
 */
export interface MinioBucketProps {
  /**
   * @schema MinioBucket#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema MinioBucket#spec
   */
  readonly spec?: MinioBucketSpec;

}

/**
 * Converts an object of type 'MinioBucketProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioBucketProps(obj: MinioBucketProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioBucketSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioBucketSpec
 */
export interface MinioBucketSpec {
  /**
   * @schema MinioBucketSpec#name
   */
  readonly name?: string;

  /**
   * @schema MinioBucketSpec#tenantRef
   */
  readonly tenantRef?: MinioBucketSpecTenantRef;

}

/**
 * Converts an object of type 'MinioBucketSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioBucketSpec(obj: MinioBucketSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'tenantRef': toJson_MinioBucketSpecTenantRef(obj.tenantRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioBucketSpecTenantRef
 */
export interface MinioBucketSpecTenantRef {
  /**
   * @schema MinioBucketSpecTenantRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioBucketSpecTenantRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'MinioBucketSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioBucketSpecTenantRef(obj: MinioBucketSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema MinioGroup
 */
export class MinioGroup extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioGroup"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioGroup',
  }

  /**
   * Renders a Kubernetes manifest for "MinioGroup".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioGroupProps = {}): any {
    return {
      ...MinioGroup.GVK,
      ...toJson_MinioGroupProps(props),
    };
  }

  /**
   * Defines a "MinioGroup" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioGroupProps = {}) {
    super(scope, id, {
      ...MinioGroup.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioGroup.GVK,
      ...toJson_MinioGroupProps(resolved),
    };
  }
}

/**
 * @schema MinioGroup
 */
export interface MinioGroupProps {
  /**
   * @schema MinioGroup#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema MinioGroup#spec
   */
  readonly spec?: MinioGroupSpec;

}

/**
 * Converts an object of type 'MinioGroupProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioGroupProps(obj: MinioGroupProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioGroupSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioGroupSpec
 */
export interface MinioGroupSpec {
  /**
   * @schema MinioGroupSpec#name
   */
  readonly name?: string;

  /**
   * @schema MinioGroupSpec#tenantRef
   */
  readonly tenantRef?: MinioGroupSpecTenantRef;

}

/**
 * Converts an object of type 'MinioGroupSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioGroupSpec(obj: MinioGroupSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'tenantRef': toJson_MinioGroupSpecTenantRef(obj.tenantRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioGroupSpecTenantRef
 */
export interface MinioGroupSpecTenantRef {
  /**
   * @schema MinioGroupSpecTenantRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioGroupSpecTenantRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'MinioGroupSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioGroupSpecTenantRef(obj: MinioGroupSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema MinioGroupBinding
 */
export class MinioGroupBinding extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioGroupBinding"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioGroupBinding',
  }

  /**
   * Renders a Kubernetes manifest for "MinioGroupBinding".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioGroupBindingProps = {}): any {
    return {
      ...MinioGroupBinding.GVK,
      ...toJson_MinioGroupBindingProps(props),
    };
  }

  /**
   * Defines a "MinioGroupBinding" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioGroupBindingProps = {}) {
    super(scope, id, {
      ...MinioGroupBinding.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioGroupBinding.GVK,
      ...toJson_MinioGroupBindingProps(resolved),
    };
  }
}

/**
 * @schema MinioGroupBinding
 */
export interface MinioGroupBindingProps {
  /**
   * @schema MinioGroupBinding#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema MinioGroupBinding#spec
   */
  readonly spec?: MinioGroupBindingSpec;

}

/**
 * Converts an object of type 'MinioGroupBindingProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioGroupBindingProps(obj: MinioGroupBindingProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioGroupBindingSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioGroupBindingSpec
 */
export interface MinioGroupBindingSpec {
  /**
   * @schema MinioGroupBindingSpec#user
   */
  readonly user?: string;

  /**
   * @schema MinioGroupBindingSpec#group
   */
  readonly group?: string;

  /**
   * @schema MinioGroupBindingSpec#tenantRef
   */
  readonly tenantRef?: MinioGroupBindingSpecTenantRef;

}

/**
 * Converts an object of type 'MinioGroupBindingSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioGroupBindingSpec(obj: MinioGroupBindingSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'user': obj.user,
    'group': obj.group,
    'tenantRef': toJson_MinioGroupBindingSpecTenantRef(obj.tenantRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioGroupBindingSpecTenantRef
 */
export interface MinioGroupBindingSpecTenantRef {
  /**
   * @schema MinioGroupBindingSpecTenantRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioGroupBindingSpecTenantRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'MinioGroupBindingSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioGroupBindingSpecTenantRef(obj: MinioGroupBindingSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema MinioPolicy
 */
export class MinioPolicy extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioPolicy"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioPolicy',
  }

  /**
   * Renders a Kubernetes manifest for "MinioPolicy".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioPolicyProps = {}): any {
    return {
      ...MinioPolicy.GVK,
      ...toJson_MinioPolicyProps(props),
    };
  }

  /**
   * Defines a "MinioPolicy" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioPolicyProps = {}) {
    super(scope, id, {
      ...MinioPolicy.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioPolicy.GVK,
      ...toJson_MinioPolicyProps(resolved),
    };
  }
}

/**
 * @schema MinioPolicy
 */
export interface MinioPolicyProps {
  /**
   * @schema MinioPolicy#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema MinioPolicy#spec
   */
  readonly spec?: MinioPolicySpec;

}

/**
 * Converts an object of type 'MinioPolicyProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicyProps(obj: MinioPolicyProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioPolicySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicySpec
 */
export interface MinioPolicySpec {
  /**
   * @schema MinioPolicySpec#name
   */
  readonly name?: string;

  /**
   * @schema MinioPolicySpec#tenantRef
   */
  readonly tenantRef?: MinioPolicySpecTenantRef;

  /**
   * @schema MinioPolicySpec#version
   */
  readonly version?: string;

  /**
   * @schema MinioPolicySpec#statement
   */
  readonly statement?: MinioPolicySpecStatement[];

}

/**
 * Converts an object of type 'MinioPolicySpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicySpec(obj: MinioPolicySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'tenantRef': toJson_MinioPolicySpecTenantRef(obj.tenantRef),
    'version': obj.version,
    'statement': obj.statement?.map(y => toJson_MinioPolicySpecStatement(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicySpecTenantRef
 */
export interface MinioPolicySpecTenantRef {
  /**
   * @schema MinioPolicySpecTenantRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioPolicySpecTenantRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'MinioPolicySpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicySpecTenantRef(obj: MinioPolicySpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicySpecStatement
 */
export interface MinioPolicySpecStatement {
  /**
   * @schema MinioPolicySpecStatement#action
   */
  readonly action?: string[];

  /**
   * @schema MinioPolicySpecStatement#resource
   */
  readonly resource?: string[];

  /**
   * @schema MinioPolicySpecStatement#effect
   */
  readonly effect?: string;

}

/**
 * Converts an object of type 'MinioPolicySpecStatement' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicySpecStatement(obj: MinioPolicySpecStatement | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'action': obj.action?.map(y => y),
    'resource': obj.resource?.map(y => y),
    'effect': obj.effect,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema MinioPolicyBinding
 */
export class MinioPolicyBinding extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioPolicyBinding"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioPolicyBinding',
  }

  /**
   * Renders a Kubernetes manifest for "MinioPolicyBinding".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioPolicyBindingProps = {}): any {
    return {
      ...MinioPolicyBinding.GVK,
      ...toJson_MinioPolicyBindingProps(props),
    };
  }

  /**
   * Defines a "MinioPolicyBinding" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioPolicyBindingProps = {}) {
    super(scope, id, {
      ...MinioPolicyBinding.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioPolicyBinding.GVK,
      ...toJson_MinioPolicyBindingProps(resolved),
    };
  }
}

/**
 * @schema MinioPolicyBinding
 */
export interface MinioPolicyBindingProps {
  /**
   * @schema MinioPolicyBinding#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema MinioPolicyBinding#spec
   */
  readonly spec?: MinioPolicyBindingSpec;

}

/**
 * Converts an object of type 'MinioPolicyBindingProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicyBindingProps(obj: MinioPolicyBindingProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioPolicyBindingSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicyBindingSpec
 */
export interface MinioPolicyBindingSpec {
  /**
   * @schema MinioPolicyBindingSpec#tenantRef
   */
  readonly tenantRef?: MinioPolicyBindingSpecTenantRef;

  /**
   * @schema MinioPolicyBindingSpec#policy
   */
  readonly policy?: string;

  /**
   * @schema MinioPolicyBindingSpec#user
   */
  readonly user?: MinioPolicyBindingSpecUser;

  /**
   * @schema MinioPolicyBindingSpec#group
   */
  readonly group?: MinioPolicyBindingSpecGroup;

}

/**
 * Converts an object of type 'MinioPolicyBindingSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicyBindingSpec(obj: MinioPolicyBindingSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'tenantRef': toJson_MinioPolicyBindingSpecTenantRef(obj.tenantRef),
    'policy': obj.policy,
    'user': toJson_MinioPolicyBindingSpecUser(obj.user),
    'group': toJson_MinioPolicyBindingSpecGroup(obj.group),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicyBindingSpecTenantRef
 */
export interface MinioPolicyBindingSpecTenantRef {
  /**
   * @schema MinioPolicyBindingSpecTenantRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioPolicyBindingSpecTenantRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'MinioPolicyBindingSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicyBindingSpecTenantRef(obj: MinioPolicyBindingSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicyBindingSpecUser
 */
export interface MinioPolicyBindingSpecUser {
  /**
   * @schema MinioPolicyBindingSpecUser#builtin
   */
  readonly builtin?: string;

  /**
   * @schema MinioPolicyBindingSpecUser#ldap
   */
  readonly ldap?: string;

}

/**
 * Converts an object of type 'MinioPolicyBindingSpecUser' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicyBindingSpecUser(obj: MinioPolicyBindingSpecUser | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'builtin': obj.builtin,
    'ldap': obj.ldap,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioPolicyBindingSpecGroup
 */
export interface MinioPolicyBindingSpecGroup {
  /**
   * @schema MinioPolicyBindingSpecGroup#builtin
   */
  readonly builtin?: string;

  /**
   * @schema MinioPolicyBindingSpecGroup#ldap
   */
  readonly ldap?: string;

}

/**
 * Converts an object of type 'MinioPolicyBindingSpecGroup' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioPolicyBindingSpecGroup(obj: MinioPolicyBindingSpecGroup | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'builtin': obj.builtin,
    'ldap': obj.ldap,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema MinioUser
 */
export class MinioUser extends ApiObject {
  /**
   * Returns the apiVersion and kind for "MinioUser"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bfiola.dev/v1',
    kind: 'MinioUser',
  }

  /**
   * Renders a Kubernetes manifest for "MinioUser".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MinioUserProps = {}): any {
    return {
      ...MinioUser.GVK,
      ...toJson_MinioUserProps(props),
    };
  }

  /**
   * Defines a "MinioUser" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MinioUserProps = {}) {
    super(scope, id, {
      ...MinioUser.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...MinioUser.GVK,
      ...toJson_MinioUserProps(resolved),
    };
  }
}

/**
 * @schema MinioUser
 */
export interface MinioUserProps {
  /**
   * @schema MinioUser#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema MinioUser#spec
   */
  readonly spec?: MinioUserSpec;

}

/**
 * Converts an object of type 'MinioUserProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioUserProps(obj: MinioUserProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_MinioUserSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioUserSpec
 */
export interface MinioUserSpec {
  /**
   * @schema MinioUserSpec#accessKey
   */
  readonly accessKey?: string;

  /**
   * @schema MinioUserSpec#secretKeyRef
   */
  readonly secretKeyRef?: MinioUserSpecSecretKeyRef;

  /**
   * @schema MinioUserSpec#tenantRef
   */
  readonly tenantRef?: MinioUserSpecTenantRef;

}

/**
 * Converts an object of type 'MinioUserSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioUserSpec(obj: MinioUserSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKey': obj.accessKey,
    'secretKeyRef': toJson_MinioUserSpecSecretKeyRef(obj.secretKeyRef),
    'tenantRef': toJson_MinioUserSpecTenantRef(obj.tenantRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioUserSpecSecretKeyRef
 */
export interface MinioUserSpecSecretKeyRef {
  /**
   * @schema MinioUserSpecSecretKeyRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioUserSpecSecretKeyRef#name
   */
  readonly name?: string;

  /**
   * @schema MinioUserSpecSecretKeyRef#key
   */
  readonly key?: string;

}

/**
 * Converts an object of type 'MinioUserSpecSecretKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioUserSpecSecretKeyRef(obj: MinioUserSpecSecretKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
    'key': obj.key,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema MinioUserSpecTenantRef
 */
export interface MinioUserSpecTenantRef {
  /**
   * @schema MinioUserSpecTenantRef#namespace
   */
  readonly namespace?: string;

  /**
   * @schema MinioUserSpecTenantRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'MinioUserSpecTenantRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MinioUserSpecTenantRef(obj: MinioUserSpecTenantRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

