// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * VerticalPodAutoscaler is the configuration for a vertical pod
autoscaler, which automatically manages pod resources based on historical and
real time resource utilization.
 *
 * @schema VerticalPodAutoscaler
 */
export class VerticalPodAutoscaler extends ApiObject {
  /**
   * Returns the apiVersion and kind for "VerticalPodAutoscaler"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'autoscaling.k8s.io/v1',
    kind: 'VerticalPodAutoscaler',
  }

  /**
   * Renders a Kubernetes manifest for "VerticalPodAutoscaler".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: VerticalPodAutoscalerProps): any {
    return {
      ...VerticalPodAutoscaler.GVK,
      ...toJson_VerticalPodAutoscalerProps(props),
    };
  }

  /**
   * Defines a "VerticalPodAutoscaler" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: VerticalPodAutoscalerProps) {
    super(scope, id, {
      ...VerticalPodAutoscaler.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...VerticalPodAutoscaler.GVK,
      ...toJson_VerticalPodAutoscalerProps(resolved),
    };
  }
}

/**
 * VerticalPodAutoscaler is the configuration for a vertical pod
 * autoscaler, which automatically manages pod resources based on historical and
 * real time resource utilization.
 *
 * @schema VerticalPodAutoscaler
 */
export interface VerticalPodAutoscalerProps {
  /**
   * @schema VerticalPodAutoscaler#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Specification of the behavior of the autoscaler.
   * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
   *
   * @schema VerticalPodAutoscaler#spec
   */
  readonly spec: VerticalPodAutoscalerSpec;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerProps(obj: VerticalPodAutoscalerProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_VerticalPodAutoscalerSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Specification of the behavior of the autoscaler.
 * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
 *
 * @schema VerticalPodAutoscalerSpec
 */
export interface VerticalPodAutoscalerSpec {
  /**
   * Recommender responsible for generating recommendation for this object.
   * List should be empty (then the default recommender will generate the
   * recommendation) or contain exactly one recommender.
   *
   * @schema VerticalPodAutoscalerSpec#recommenders
   */
  readonly recommenders?: VerticalPodAutoscalerSpecRecommenders[];

  /**
   * Controls how the autoscaler computes recommended resources.
   * The resource policy may be used to set constraints on the recommendations
   * for individual containers.
   * If any individual containers need to be excluded from getting the VPA recommendations, then
   * it must be disabled explicitly by setting mode to "Off" under containerPolicies.
   * If not specified, the autoscaler computes recommended resources for all containers in the pod,
   * without additional constraints.
   *
   * @schema VerticalPodAutoscalerSpec#resourcePolicy
   */
  readonly resourcePolicy?: VerticalPodAutoscalerSpecResourcePolicy;

  /**
   * TargetRef points to the controller managing the set of pods for the
   * autoscaler to control - e.g. Deployment, StatefulSet. VerticalPodAutoscaler
   * can be targeted at controller implementing scale subresource (the pod set is
   * retrieved from the controller's ScaleStatus) or some well known controllers
   * (e.g. for DaemonSet the pod set is read from the controller's spec).
   * If VerticalPodAutoscaler cannot use specified target it will report
   * ConfigUnsupported condition.
   * Note that VerticalPodAutoscaler does not require full implementation
   * of scale subresource - it will not use it to modify the replica count.
   * The only thing retrieved is a label selector matching pods grouped by
   * the target resource.
   *
   * @schema VerticalPodAutoscalerSpec#targetRef
   */
  readonly targetRef: VerticalPodAutoscalerSpecTargetRef;

  /**
   * Describes the rules on how changes are applied to the pods.
   * If not specified, all fields in the `PodUpdatePolicy` are set to their
   * default values.
   *
   * @schema VerticalPodAutoscalerSpec#updatePolicy
   */
  readonly updatePolicy?: VerticalPodAutoscalerSpecUpdatePolicy;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpec(obj: VerticalPodAutoscalerSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'recommenders': obj.recommenders?.map(y => toJson_VerticalPodAutoscalerSpecRecommenders(y)),
    'resourcePolicy': toJson_VerticalPodAutoscalerSpecResourcePolicy(obj.resourcePolicy),
    'targetRef': toJson_VerticalPodAutoscalerSpecTargetRef(obj.targetRef),
    'updatePolicy': toJson_VerticalPodAutoscalerSpecUpdatePolicy(obj.updatePolicy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * VerticalPodAutoscalerRecommenderSelector points to a specific Vertical Pod Autoscaler recommender.
 * In the future it might pass parameters to the recommender.
 *
 * @schema VerticalPodAutoscalerSpecRecommenders
 */
export interface VerticalPodAutoscalerSpecRecommenders {
  /**
   * Name of the recommender responsible for generating recommendation for this object.
   *
   * @schema VerticalPodAutoscalerSpecRecommenders#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpecRecommenders' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpecRecommenders(obj: VerticalPodAutoscalerSpecRecommenders | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Controls how the autoscaler computes recommended resources.
 * The resource policy may be used to set constraints on the recommendations
 * for individual containers.
 * If any individual containers need to be excluded from getting the VPA recommendations, then
 * it must be disabled explicitly by setting mode to "Off" under containerPolicies.
 * If not specified, the autoscaler computes recommended resources for all containers in the pod,
 * without additional constraints.
 *
 * @schema VerticalPodAutoscalerSpecResourcePolicy
 */
export interface VerticalPodAutoscalerSpecResourcePolicy {
  /**
   * Per-container resource policies.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicy#containerPolicies
   */
  readonly containerPolicies?: VerticalPodAutoscalerSpecResourcePolicyContainerPolicies[];
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpecResourcePolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpecResourcePolicy(obj: VerticalPodAutoscalerSpecResourcePolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'containerPolicies': obj.containerPolicies?.map(y => toJson_VerticalPodAutoscalerSpecResourcePolicyContainerPolicies(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * TargetRef points to the controller managing the set of pods for the
 * autoscaler to control - e.g. Deployment, StatefulSet. VerticalPodAutoscaler
 * can be targeted at controller implementing scale subresource (the pod set is
 * retrieved from the controller's ScaleStatus) or some well known controllers
 * (e.g. for DaemonSet the pod set is read from the controller's spec).
 * If VerticalPodAutoscaler cannot use specified target it will report
 * ConfigUnsupported condition.
 * Note that VerticalPodAutoscaler does not require full implementation
 * of scale subresource - it will not use it to modify the replica count.
 * The only thing retrieved is a label selector matching pods grouped by
 * the target resource.
 *
 * @schema VerticalPodAutoscalerSpecTargetRef
 */
export interface VerticalPodAutoscalerSpecTargetRef {
  /**
   * apiVersion is the API version of the referent
   *
   * @schema VerticalPodAutoscalerSpecTargetRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   *
   * @schema VerticalPodAutoscalerSpecTargetRef#kind
   */
  readonly kind: string;

  /**
   * name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   *
   * @schema VerticalPodAutoscalerSpecTargetRef#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpecTargetRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpecTargetRef(obj: VerticalPodAutoscalerSpecTargetRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'apiVersion': obj.apiVersion,
    'kind': obj.kind,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Describes the rules on how changes are applied to the pods.
 * If not specified, all fields in the `PodUpdatePolicy` are set to their
 * default values.
 *
 * @schema VerticalPodAutoscalerSpecUpdatePolicy
 */
export interface VerticalPodAutoscalerSpecUpdatePolicy {
  /**
   * EvictionRequirements is a list of EvictionRequirements that need to
   * evaluate to true in order for a Pod to be evicted. If more than one
   * EvictionRequirement is specified, all of them need to be fulfilled to allow eviction.
   *
   * @schema VerticalPodAutoscalerSpecUpdatePolicy#evictionRequirements
   */
  readonly evictionRequirements?: VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements[];

  /**
   * Minimal number of replicas which need to be alive for Updater to attempt
   * pod eviction (pending other checks like PDB). Only positive values are
   * allowed. Overrides global '--min-replicas' flag.
   *
   * @schema VerticalPodAutoscalerSpecUpdatePolicy#minReplicas
   */
  readonly minReplicas?: number;

  /**
   * Controls when autoscaler applies changes to the pod resources.
   * The default is 'Recreate'.
   *
   * @schema VerticalPodAutoscalerSpecUpdatePolicy#updateMode
   */
  readonly updateMode?: VerticalPodAutoscalerSpecUpdatePolicyUpdateMode;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpecUpdatePolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpecUpdatePolicy(obj: VerticalPodAutoscalerSpecUpdatePolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'evictionRequirements': obj.evictionRequirements?.map(y => toJson_VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements(y)),
    'minReplicas': obj.minReplicas,
    'updateMode': obj.updateMode,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ContainerResourcePolicy controls how autoscaler computes the recommended
 * resources for a specific container.
 *
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies
 */
export interface VerticalPodAutoscalerSpecResourcePolicyContainerPolicies {
  /**
   * Name of the container or DefaultContainerResourcePolicy, in which
   * case the policy is used by the containers that don't have their own
   * policy specified.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#containerName
   */
  readonly containerName?: string;

  /**
   * Specifies the type of recommendations that will be computed
   * (and possibly applied) by VPA.
   * If not specified, the default of [ResourceCPU, ResourceMemory] will be used.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#controlledResources
   */
  readonly controlledResources?: string[];

  /**
   * Specifies which resource values should be controlled.
   * The default is "RequestsAndLimits".
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#controlledValues
   */
  readonly controlledValues?: VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesControlledValues;

  /**
   * Specifies the maximum amount of resources that will be recommended
   * for the container. The default is no maximum.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#maxAllowed
   */
  readonly maxAllowed?: { [key: string]: VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed };

  /**
   * Specifies the minimal amount of resources that will be recommended
   * for the container. The default is no minimum.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#minAllowed
   */
  readonly minAllowed?: { [key: string]: VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed };

  /**
   * Whether autoscaler is enabled for the container. The default is "Auto".
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#mode
   */
  readonly mode?: VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMode;

  /**
   * oomBumpUpRatio is the ratio to increase memory when OOM is detected.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#oomBumpUpRatio
   */
  readonly oomBumpUpRatio?: VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio;

  /**
   * oomMinBumpUp is the minimum increase in memory when OOM is detected.
   *
   * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPolicies#oomMinBumpUp
   */
  readonly oomMinBumpUp?: VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpecResourcePolicyContainerPolicies' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpecResourcePolicyContainerPolicies(obj: VerticalPodAutoscalerSpecResourcePolicyContainerPolicies | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'containerName': obj.containerName,
    'controlledResources': obj.controlledResources?.map(y => y),
    'controlledValues': obj.controlledValues,
    'maxAllowed': ((obj.maxAllowed) === undefined) ? undefined : (Object.entries(obj.maxAllowed).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }), {})),
    'minAllowed': ((obj.minAllowed) === undefined) ? undefined : (Object.entries(obj.minAllowed).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }), {})),
    'mode': obj.mode,
    'oomBumpUpRatio': obj.oomBumpUpRatio?.value,
    'oomMinBumpUp': obj.oomMinBumpUp?.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * EvictionRequirement defines a single condition which needs to be true in
 * order to evict a Pod
 *
 * @schema VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements
 */
export interface VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements {
  /**
   * EvictionChangeRequirement refers to the relationship between the new target recommendation for a Pod and its current requests, what kind of change is necessary for the Pod to be evicted
   *
   * @schema VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements#changeRequirement
   */
  readonly changeRequirement: VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirementsChangeRequirement;

  /**
   * Resources is a list of one or more resources that the condition applies
   * to. If more than one resource is given, the EvictionRequirement is fulfilled
   * if at least one resource meets `changeRequirement`.
   *
   * @schema VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements#resources
   */
  readonly resources: string[];
}

/**
 * Converts an object of type 'VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements(obj: VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirements | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'changeRequirement': obj.changeRequirement,
    'resources': obj.resources?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Controls when autoscaler applies changes to the pod resources.
 * The default is 'Recreate'.
 *
 * @schema VerticalPodAutoscalerSpecUpdatePolicyUpdateMode
 */
export enum VerticalPodAutoscalerSpecUpdatePolicyUpdateMode {
  /** Off */
  OFF = "Off",
  /** Initial */
  INITIAL = "Initial",
  /** Recreate */
  RECREATE = "Recreate",
  /** InPlaceOrRecreate */
  IN_PLACE_OR_RECREATE = "InPlaceOrRecreate",
  /** Auto */
  AUTO = "Auto",
}

/**
 * Specifies which resource values should be controlled.
 * The default is "RequestsAndLimits".
 *
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesControlledValues
 */
export enum VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesControlledValues {
  /** RequestsAndLimits */
  REQUESTS_AND_LIMITS = "RequestsAndLimits",
  /** RequestsOnly */
  REQUESTS_ONLY = "RequestsOnly",
}

/**
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed
 */
export class VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed {
  public static fromNumber(value: number): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed(value);
  }
  public static fromString(value: string): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMaxAllowed(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed
 */
export class VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed {
  public static fromNumber(value: number): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed(value);
  }
  public static fromString(value: string): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMinAllowed(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * Whether autoscaler is enabled for the container. The default is "Auto".
 *
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMode
 */
export enum VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesMode {
  /** Auto */
  AUTO = "Auto",
  /** Off */
  OFF = "Off",
}

/**
 * oomBumpUpRatio is the ratio to increase memory when OOM is detected.
 *
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio
 */
export class VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio {
  public static fromNumber(value: number): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio(value);
  }
  public static fromString(value: string): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomBumpUpRatio(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * oomMinBumpUp is the minimum increase in memory when OOM is detected.
 *
 * @schema VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp
 */
export class VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp {
  public static fromNumber(value: number): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp(value);
  }
  public static fromString(value: string): VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp {
    return new VerticalPodAutoscalerSpecResourcePolicyContainerPoliciesOomMinBumpUp(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * EvictionChangeRequirement refers to the relationship between the new target recommendation for a Pod and its current requests, what kind of change is necessary for the Pod to be evicted
 *
 * @schema VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirementsChangeRequirement
 */
export enum VerticalPodAutoscalerSpecUpdatePolicyEvictionRequirementsChangeRequirement {
  /** TargetHigherThanRequests */
  TARGET_HIGHER_THAN_REQUESTS = "TargetHigherThanRequests",
  /** TargetLowerThanRequests */
  TARGET_LOWER_THAN_REQUESTS = "TargetLowerThanRequests",
}


/**
 * VerticalPodAutoscaler is the configuration for a vertical pod
autoscaler, which automatically manages pod resources based on historical and
real time resource utilization.
 *
 * @schema VerticalPodAutoscalerV1Beta2
 */
export class VerticalPodAutoscalerV1Beta2 extends ApiObject {
  /**
   * Returns the apiVersion and kind for "VerticalPodAutoscalerV1Beta2"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'autoscaling.k8s.io/v1beta2',
    kind: 'VerticalPodAutoscaler',
  }

  /**
   * Renders a Kubernetes manifest for "VerticalPodAutoscalerV1Beta2".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: VerticalPodAutoscalerV1Beta2Props): any {
    return {
      ...VerticalPodAutoscalerV1Beta2.GVK,
      ...toJson_VerticalPodAutoscalerV1Beta2Props(props),
    };
  }

  /**
   * Defines a "VerticalPodAutoscalerV1Beta2" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: VerticalPodAutoscalerV1Beta2Props) {
    super(scope, id, {
      ...VerticalPodAutoscalerV1Beta2.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...VerticalPodAutoscalerV1Beta2.GVK,
      ...toJson_VerticalPodAutoscalerV1Beta2Props(resolved),
    };
  }
}

/**
 * VerticalPodAutoscaler is the configuration for a vertical pod
 * autoscaler, which automatically manages pod resources based on historical and
 * real time resource utilization.
 *
 * @schema VerticalPodAutoscalerV1Beta2
 */
export interface VerticalPodAutoscalerV1Beta2Props {
  /**
   * @schema VerticalPodAutoscalerV1Beta2#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Specification of the behavior of the autoscaler.
   * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
   *
   * @schema VerticalPodAutoscalerV1Beta2#spec
   */
  readonly spec: VerticalPodAutoscalerV1Beta2Spec;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerV1Beta2Props' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerV1Beta2Props(obj: VerticalPodAutoscalerV1Beta2Props | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_VerticalPodAutoscalerV1Beta2Spec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Specification of the behavior of the autoscaler.
 * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
 *
 * @schema VerticalPodAutoscalerV1Beta2Spec
 */
export interface VerticalPodAutoscalerV1Beta2Spec {
  /**
   * Controls how the autoscaler computes recommended resources.
   * The resource policy may be used to set constraints on the recommendations
   * for individual containers. If not specified, the autoscaler computes recommended
   * resources for all containers in the pod, without additional constraints.
   *
   * @schema VerticalPodAutoscalerV1Beta2Spec#resourcePolicy
   */
  readonly resourcePolicy?: VerticalPodAutoscalerV1Beta2SpecResourcePolicy;

  /**
   * TargetRef points to the controller managing the set of pods for the
   * autoscaler to control - e.g. Deployment, StatefulSet. VerticalPodAutoscaler
   * can be targeted at controller implementing scale subresource (the pod set is
   * retrieved from the controller's ScaleStatus) or some well known controllers
   * (e.g. for DaemonSet the pod set is read from the controller's spec).
   * If VerticalPodAutoscaler cannot use specified target it will report
   * ConfigUnsupported condition.
   * Note that VerticalPodAutoscaler does not require full implementation
   * of scale subresource - it will not use it to modify the replica count.
   * The only thing retrieved is a label selector matching pods grouped by
   * the target resource.
   *
   * @schema VerticalPodAutoscalerV1Beta2Spec#targetRef
   */
  readonly targetRef: VerticalPodAutoscalerV1Beta2SpecTargetRef;

  /**
   * Describes the rules on how changes are applied to the pods.
   * If not specified, all fields in the `PodUpdatePolicy` are set to their
   * default values.
   *
   * @schema VerticalPodAutoscalerV1Beta2Spec#updatePolicy
   */
  readonly updatePolicy?: VerticalPodAutoscalerV1Beta2SpecUpdatePolicy;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerV1Beta2Spec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerV1Beta2Spec(obj: VerticalPodAutoscalerV1Beta2Spec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resourcePolicy': toJson_VerticalPodAutoscalerV1Beta2SpecResourcePolicy(obj.resourcePolicy),
    'targetRef': toJson_VerticalPodAutoscalerV1Beta2SpecTargetRef(obj.targetRef),
    'updatePolicy': toJson_VerticalPodAutoscalerV1Beta2SpecUpdatePolicy(obj.updatePolicy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Controls how the autoscaler computes recommended resources.
 * The resource policy may be used to set constraints on the recommendations
 * for individual containers. If not specified, the autoscaler computes recommended
 * resources for all containers in the pod, without additional constraints.
 *
 * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicy
 */
export interface VerticalPodAutoscalerV1Beta2SpecResourcePolicy {
  /**
   * Per-container resource policies.
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicy#containerPolicies
   */
  readonly containerPolicies?: VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies[];
}

/**
 * Converts an object of type 'VerticalPodAutoscalerV1Beta2SpecResourcePolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerV1Beta2SpecResourcePolicy(obj: VerticalPodAutoscalerV1Beta2SpecResourcePolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'containerPolicies': obj.containerPolicies?.map(y => toJson_VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * TargetRef points to the controller managing the set of pods for the
 * autoscaler to control - e.g. Deployment, StatefulSet. VerticalPodAutoscaler
 * can be targeted at controller implementing scale subresource (the pod set is
 * retrieved from the controller's ScaleStatus) or some well known controllers
 * (e.g. for DaemonSet the pod set is read from the controller's spec).
 * If VerticalPodAutoscaler cannot use specified target it will report
 * ConfigUnsupported condition.
 * Note that VerticalPodAutoscaler does not require full implementation
 * of scale subresource - it will not use it to modify the replica count.
 * The only thing retrieved is a label selector matching pods grouped by
 * the target resource.
 *
 * @schema VerticalPodAutoscalerV1Beta2SpecTargetRef
 */
export interface VerticalPodAutoscalerV1Beta2SpecTargetRef {
  /**
   * apiVersion is the API version of the referent
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecTargetRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecTargetRef#kind
   */
  readonly kind: string;

  /**
   * name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecTargetRef#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerV1Beta2SpecTargetRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerV1Beta2SpecTargetRef(obj: VerticalPodAutoscalerV1Beta2SpecTargetRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'apiVersion': obj.apiVersion,
    'kind': obj.kind,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Describes the rules on how changes are applied to the pods.
 * If not specified, all fields in the `PodUpdatePolicy` are set to their
 * default values.
 *
 * @schema VerticalPodAutoscalerV1Beta2SpecUpdatePolicy
 */
export interface VerticalPodAutoscalerV1Beta2SpecUpdatePolicy {
  /**
   * Controls when autoscaler applies changes to the pod resources.
   * The default is 'Auto'.
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecUpdatePolicy#updateMode
   */
  readonly updateMode?: VerticalPodAutoscalerV1Beta2SpecUpdatePolicyUpdateMode;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerV1Beta2SpecUpdatePolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerV1Beta2SpecUpdatePolicy(obj: VerticalPodAutoscalerV1Beta2SpecUpdatePolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'updateMode': obj.updateMode,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ContainerResourcePolicy controls how autoscaler computes the recommended
 * resources for a specific container.
 *
 * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies
 */
export interface VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies {
  /**
   * Name of the container or DefaultContainerResourcePolicy, in which
   * case the policy is used by the containers that don't have their own
   * policy specified.
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies#containerName
   */
  readonly containerName?: string;

  /**
   * Specifies the maximum amount of resources that will be recommended
   * for the container. The default is no maximum.
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies#maxAllowed
   */
  readonly maxAllowed?: { [key: string]: VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed };

  /**
   * Specifies the minimal amount of resources that will be recommended
   * for the container. The default is no minimum.
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies#minAllowed
   */
  readonly minAllowed?: { [key: string]: VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed };

  /**
   * Whether autoscaler is enabled for the container. The default is "Auto".
   *
   * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies#mode
   */
  readonly mode?: VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMode;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies(obj: VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPolicies | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'containerName': obj.containerName,
    'maxAllowed': ((obj.maxAllowed) === undefined) ? undefined : (Object.entries(obj.maxAllowed).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }), {})),
    'minAllowed': ((obj.minAllowed) === undefined) ? undefined : (Object.entries(obj.minAllowed).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }), {})),
    'mode': obj.mode,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Controls when autoscaler applies changes to the pod resources.
 * The default is 'Auto'.
 *
 * @schema VerticalPodAutoscalerV1Beta2SpecUpdatePolicyUpdateMode
 */
export enum VerticalPodAutoscalerV1Beta2SpecUpdatePolicyUpdateMode {
  /** Off */
  OFF = "Off",
  /** Initial */
  INITIAL = "Initial",
  /** Recreate */
  RECREATE = "Recreate",
  /** Auto */
  AUTO = "Auto",
}

/**
 * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed
 */
export class VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed {
  public static fromNumber(value: number): VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed {
    return new VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed(value);
  }
  public static fromString(value: string): VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed {
    return new VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMaxAllowed(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed
 */
export class VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed {
  public static fromNumber(value: number): VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed {
    return new VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed(value);
  }
  public static fromString(value: string): VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed {
    return new VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMinAllowed(value);
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * Whether autoscaler is enabled for the container. The default is "Auto".
 *
 * @schema VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMode
 */
export enum VerticalPodAutoscalerV1Beta2SpecResourcePolicyContainerPoliciesMode {
  /** Auto */
  AUTO = "Auto",
  /** Off */
  OFF = "Off",
}


/**
 * VerticalPodAutoscalerCheckpoint is the checkpoint of the internal state of VPA that
is used for recovery after recommender's restart.
 *
 * @schema VerticalPodAutoscalerCheckpoint
 */
export class VerticalPodAutoscalerCheckpoint extends ApiObject {
  /**
   * Returns the apiVersion and kind for "VerticalPodAutoscalerCheckpoint"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'autoscaling.k8s.io/v1',
    kind: 'VerticalPodAutoscalerCheckpoint',
  }

  /**
   * Renders a Kubernetes manifest for "VerticalPodAutoscalerCheckpoint".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: VerticalPodAutoscalerCheckpointProps = {}): any {
    return {
      ...VerticalPodAutoscalerCheckpoint.GVK,
      ...toJson_VerticalPodAutoscalerCheckpointProps(props),
    };
  }

  /**
   * Defines a "VerticalPodAutoscalerCheckpoint" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: VerticalPodAutoscalerCheckpointProps = {}) {
    super(scope, id, {
      ...VerticalPodAutoscalerCheckpoint.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...VerticalPodAutoscalerCheckpoint.GVK,
      ...toJson_VerticalPodAutoscalerCheckpointProps(resolved),
    };
  }
}

/**
 * VerticalPodAutoscalerCheckpoint is the checkpoint of the internal state of VPA that
 * is used for recovery after recommender's restart.
 *
 * @schema VerticalPodAutoscalerCheckpoint
 */
export interface VerticalPodAutoscalerCheckpointProps {
  /**
   * @schema VerticalPodAutoscalerCheckpoint#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Specification of the checkpoint.
   * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
   *
   * @schema VerticalPodAutoscalerCheckpoint#spec
   */
  readonly spec?: VerticalPodAutoscalerCheckpointSpec;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerCheckpointProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerCheckpointProps(obj: VerticalPodAutoscalerCheckpointProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_VerticalPodAutoscalerCheckpointSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Specification of the checkpoint.
 * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
 *
 * @schema VerticalPodAutoscalerCheckpointSpec
 */
export interface VerticalPodAutoscalerCheckpointSpec {
  /**
   * Name of the checkpointed container.
   *
   * @schema VerticalPodAutoscalerCheckpointSpec#containerName
   */
  readonly containerName?: string;

  /**
   * Name of the VPA object that stored VerticalPodAutoscalerCheckpoint object.
   *
   * @schema VerticalPodAutoscalerCheckpointSpec#vpaObjectName
   */
  readonly vpaObjectName?: string;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerCheckpointSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerCheckpointSpec(obj: VerticalPodAutoscalerCheckpointSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'containerName': obj.containerName,
    'vpaObjectName': obj.vpaObjectName,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * VerticalPodAutoscalerCheckpoint is the checkpoint of the internal state of VPA that
is used for recovery after recommender's restart.
 *
 * @schema VerticalPodAutoscalerCheckpointV1Beta2
 */
export class VerticalPodAutoscalerCheckpointV1Beta2 extends ApiObject {
  /**
   * Returns the apiVersion and kind for "VerticalPodAutoscalerCheckpointV1Beta2"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'autoscaling.k8s.io/v1beta2',
    kind: 'VerticalPodAutoscalerCheckpoint',
  }

  /**
   * Renders a Kubernetes manifest for "VerticalPodAutoscalerCheckpointV1Beta2".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: VerticalPodAutoscalerCheckpointV1Beta2Props = {}): any {
    return {
      ...VerticalPodAutoscalerCheckpointV1Beta2.GVK,
      ...toJson_VerticalPodAutoscalerCheckpointV1Beta2Props(props),
    };
  }

  /**
   * Defines a "VerticalPodAutoscalerCheckpointV1Beta2" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: VerticalPodAutoscalerCheckpointV1Beta2Props = {}) {
    super(scope, id, {
      ...VerticalPodAutoscalerCheckpointV1Beta2.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...VerticalPodAutoscalerCheckpointV1Beta2.GVK,
      ...toJson_VerticalPodAutoscalerCheckpointV1Beta2Props(resolved),
    };
  }
}

/**
 * VerticalPodAutoscalerCheckpoint is the checkpoint of the internal state of VPA that
 * is used for recovery after recommender's restart.
 *
 * @schema VerticalPodAutoscalerCheckpointV1Beta2
 */
export interface VerticalPodAutoscalerCheckpointV1Beta2Props {
  /**
   * @schema VerticalPodAutoscalerCheckpointV1Beta2#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Specification of the checkpoint.
   * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
   *
   * @schema VerticalPodAutoscalerCheckpointV1Beta2#spec
   */
  readonly spec?: VerticalPodAutoscalerCheckpointV1Beta2Spec;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerCheckpointV1Beta2Props' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerCheckpointV1Beta2Props(obj: VerticalPodAutoscalerCheckpointV1Beta2Props | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_VerticalPodAutoscalerCheckpointV1Beta2Spec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Specification of the checkpoint.
 * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
 *
 * @schema VerticalPodAutoscalerCheckpointV1Beta2Spec
 */
export interface VerticalPodAutoscalerCheckpointV1Beta2Spec {
  /**
   * Name of the checkpointed container.
   *
   * @schema VerticalPodAutoscalerCheckpointV1Beta2Spec#containerName
   */
  readonly containerName?: string;

  /**
   * Name of the VPA object that stored VerticalPodAutoscalerCheckpoint object.
   *
   * @schema VerticalPodAutoscalerCheckpointV1Beta2Spec#vpaObjectName
   */
  readonly vpaObjectName?: string;
}

/**
 * Converts an object of type 'VerticalPodAutoscalerCheckpointV1Beta2Spec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_VerticalPodAutoscalerCheckpointV1Beta2Spec(obj: VerticalPodAutoscalerCheckpointV1Beta2Spec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'containerName': obj.containerName,
    'vpaObjectName': obj.vpaObjectName,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

