listener 1883
plugin /usr/lib/mosquitto_persist_sqlite.so
persistence_location /mosquitto/data/
plugin /usr/lib/mosquitto_password_file.so
plugin_opt_password_file /auth/password_file
acl_file /mosquitto/config/acl.conf
