- template: alertmanager
- template: alloy
- template: bucket-sync
- template: cert-manager
- template: cilium
- template: envoy-gateway
- template: dynamic-dns
- template: external-dns
- template: external-snapshotter
- template: flux-bootstrap
  flux: false
- template: garage
- template: garage-operator
- template: gateway
- template: gateway-api
- template: gateway-route-sync
- template: grafana
- template: grafana-operator
- template: kube-state-metrics
- template: linstor
- template: loki
- template: metrics-server
- template: minecraft
- template: monitoring-config
- template: network-policy
- template: piraeus-operator
- template: postfix
- template: prometheus
- template: prometheus-node-exporter
- template: prometheus-operator
- template: pvc-restore
- template: router-policy-sync
- template: seven-days-to-die
- id: single-player-tarkov-3
  template: single-player-tarkov
  options:
    subdomain: spt-3
    port: 6969
    version: 3.11.4
- id: single-player-tarkov-4
  template: single-player-tarkov
  options:
    subdomain: spt-4
    port: 6970
    version: 4.0.13
- template: storage-class
- template: tunnel
- template: vault
- template: vault-push-secrets
- template: vault-secrets-operator
- template: vertical-pod-autoscaler
- template: volsync
- template: volsync-testing
- template: volume-snapshot-api
