apiVersion: v1alpha1
kind: HomelabClusterConfig
endpoint: cluster.fiola.dev
hardware:
  axp:
    disks:
      SYSTEM:
        device: /dev/nvme0n1
      EPHEMERAL:
        device: /dev/nvme0n1
        size: 200GiB
      linstor:
        device: /dev/nvme0n1
        size: 1600GiB
    imageConfig:
      filename: metal-amd64.iso
      schematic:
        customization:
          systemExtensions:
            officialExtensions:
              - siderolabs/drbd
              - siderolabs/nvidia-container-toolkit-lts
              - siderolabs/nvidia-open-gpu-kernel-modules-lts
    image: factory.talos.dev/metal-installer/79770bff8ecabad8e2f0bc8ef58f121a41af55e31e4e4ec2b3b0d1d00b10cb1d:v1.13.3
    machineConfig:
      machine:
        kernel:
          modules:
            - name: nvidia
            - name: nvidia_uvm
            - name: nvidia_drm
            - name: nvidia_modeset
  tc:
    disks:
      SYSTEM:
        device: /dev/nvme0n1
      EPHEMERAL:
        device: /dev/nvme0n1
        size: 200GiB
      linstor:
        device: /dev/nvme0n1
        size: 1600GiB
    imageConfig:
      filename: metal-amd64.iso
      schematic:
        customization:
          systemExtensions:
            officialExtensions:
              - siderolabs/drbd
              - siderolabs/i915
    image: factory.talos.dev/metal-installer/322dbdfae3877a291f8977311656b2267aacfe7c15a483f56904d65050814a0c:v1.13.3
kubernetes: 1.36.1
name: homelab
---
cluster:
  allowSchedulingOnControlPlanes: true
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          defaults:
            audit: restricted
            enforce: restricted
            warn: restricted
  controllerManager:
    extraArgs:
      # allow remote-node workloads to access server (monitoring)
      bind-address: 0.0.0.0
  network:
    cni:
      # disable cni (cilium)
      name: none
  proxy:
    # disable kube-proxy (cilium)
    disabled: true
  scheduler:
    extraArgs:
      # allow remote-node workloads to access server (monitoring)
      bind-address: 0.0.0.0
machine:
  features:
    hostDNS:
      # disable dns forwarding (cilium)
      forwardKubeDNSToHost: false
  kernel:
    modules:
      # configure drbd kernel modules (piraeus)
      - name: dm_mod
      - name: dm_thin_pool
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
  kubelet:
    extraConfig:
      # ensure the scheduler leaves buffer for system/kube workloads
      systemReserved:
        cpu: "250m"
        memory: "512Mi"
      kubeReserved:
        cpu: "250m"
        memory: "512Mi"
    extraMounts:
      # configure r/w mounts (piraeus)
      - destination: /var/local
        source: /var/local
        type: bind
        options:
          - rbind
          - rshared
          - rw
---
apiVersion: v1alpha1
kind: BridgeConfig
name: mdns0
links: []
up: true
addresses:
  - address: 169.254.254.1/24
---
apiVersion: v1alpha1
kind: HomelabNodeConfig
hardware: tc
hostname: samoyed.cluster.fiola.dev
role: controlplane
interface: eno1
---
apiVersion: v1alpha1
kind: HomelabNodeConfig
hardware: tc
hostname: chihuahua.cluster.fiola.dev
role: worker
interface: eno2
---
apiVersion: v1alpha1
kind: HomelabNodeConfig
hardware: tc
hostname: husky.cluster.fiola.dev
role: worker
interface: eno2
---
apiVersion: v1alpha1
kind: HomelabNodeConfig
hardware: tc
hostname: malamute.cluster.fiola.dev
role: worker
interface: eno2
---
apiVersion: v1alpha1
kind: HomelabNodeConfig
hardware: axp
hostname: shiba.cluster.fiola.dev
role: worker
interface: enp196s0