apiVersion: v1alpha1
kind: HomelabNetworkConfig
outputs:
  - file: ap.office.sh
    template: network-ap.sh
    inputs:
      hostname: office.ap

  - file: ap.living-room.sh
    template: network-ap.sh
    inputs:
      hostname: living-room.ap

  - file: ap.bedroom-2.sh
    template: network-ap.sh
    inputs:
      hostname: bedroom-2.ap

  - file: router.rsc
    template: network-router.rsc

  - file: switch.core.yaml
    template: network-switch.core.yaml

  - file: switch.cluster.yaml
    template: network-switch.cluster.yaml

  - file: wireguard.bfiola-desktop-infrastructure.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaDesktop.infrastructure.private}"
      address: 192.168.34.3/32
      publicKey: "${secrets.wireguard.interfaces.infrastructure.public}"
      port: 13233
      allowedIps:
        - 192.168.32.0/23
        - 192.168.88.1/32

  - file: wireguard.bfiola-desktop-management.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaDesktop.management.private}"
      address: 192.168.89.3/32
      publicKey: "${secrets.wireguard.interfaces.management.public}"
      port: 13234
      allowedIps:
        - 192.168.88.0/24

  - file: wireguard.bfiola-home-laptop-personal.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaHomeLaptop.personal.private}"
      address: 192.168.17.2/32
      publicKey: "${secrets.wireguard.interfaces.personal.public}"
      port: 13232
      allowedIps:
        - 192.168.33.2/32
        - 192.168.33.3/32
        - 192.168.33.7/32
        - 192.168.88.1/32

  - file: wireguard.bfiola-home-laptop-infrastructure.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaHomeLaptop.infrastructure.private}"
      address: 192.168.34.2/32
      publicKey: "${secrets.wireguard.interfaces.infrastructure.public}"
      port: 13233
      allowedIps:
        - 192.168.32.0/23
        - 192.168.88.1/32

  - file: wireguard.bfiola-home-laptop-management.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaHomeLaptop.management.private}"
      address: 192.168.89.2/32
      publicKey: "${secrets.wireguard.interfaces.management.public}"
      port: 13234
      allowedIps:
        - 192.168.88.0/24

  - file: wireguard.bfiola-iphone.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaIphone.personal.private}"
      address: 192.168.17.4/32
      publicKey: "${secrets.wireguard.interfaces.personal.public}"
      port: 13232
      allowedIps:
        - 192.168.33.2/32
        - 192.168.33.3/32
        - 192.168.33.7/32
        - 192.168.88.1/32

  - file: wireguard.bfiola-work-laptop-personal.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaWorkLaptop.personal.private}"
      address: 192.168.17.3/32
      publicKey: "${secrets.wireguard.interfaces.personal.public}"
      port: 13232
      allowedIps:
        - 192.168.33.2/32
        - 192.168.33.3/32
        - 192.168.33.7/32
        - 192.168.88.1/32

  - file: wireguard.bfiola-work-laptop-infrastructure.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaWorkLaptop.infrastructure.private}"
      address: 192.168.34.4/32
      publicKey: "${secrets.wireguard.interfaces.infrastructure.public}"
      port: 13233
      allowedIps:
        - 192.168.32.0/23
        - 192.168.88.1/32

  - file: wireguard.bfiola-work-laptop-management.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaWorkLaptop.management.private}"
      address: 192.168.89.4/32
      publicKey: "${secrets.wireguard.interfaces.management.public}"
      port: 13234
      allowedIps:
        - 192.168.88.0/24

  - file: wireguard.jfiola-iphone.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.jfiolaIphone.family.private}"
      address: 192.168.9.2/32
      publicKey: "${secrets.wireguard.interfaces.family.public}"
      port: 13231
      allowedIps:
        - 192.168.33.2/32
        - 192.168.33.7/32
        - 192.168.88.1/32

  - file: wireguard.ph.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.ph.friends.private}"
      address: 192.168.41.2/32
      publicKey: "${secrets.wireguard.interfaces.friends.public}"
      port: 13235
      allowedIps:
        - 192.168.33.7/32
        - 192.168.88.1/32
