apiVersion: v1alpha1
kind: HomelabNetworkConfig
outputs:
  - file: router.rsc
    template: network-router.rsc

  - file: ap.office.sh
    template: network-ap.sh
    inputs:
      hostname: office.ap

  - file: ap.living-room.sh
    template: network-ap.sh
    inputs:
      hostname: living-room.ap

  - file: ap.bedroom-2.sh
    template: network-ap.sh
    inputs:
      hostname: bedroom-2.ap

  - file: wireguard.bfiola-desktop-infrastructure.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaDesktop.infrastructure.private}"
      address: 192.168.34.3/32
      publicKey: "${secrets.wireguard.interfaces.infrastructure.public}"
      port: 13233

  - file: wireguard.bfiola-desktop-management.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaDesktop.management.private}"
      address: 192.168.89.3/32
      publicKey: "${secrets.wireguard.interfaces.management.public}"
      port: 13234

  - file: wireguard.bfiola-home-laptop-personal.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaHomeLaptop.personal.private}"
      address: 192.168.17.2/32
      publicKey: "${secrets.wireguard.interfaces.personal.public}"
      port: 13232

  - file: wireguard.bfiola-home-laptop-infrastructure.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaHomeLaptop.infrastructure.private}"
      address: 192.168.34.2/32
      publicKey: "${secrets.wireguard.interfaces.infrastructure.public}"
      port: 13233

  - file: wireguard.bfiola-home-laptop-management.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.bfiolaHomeLaptop.management.private}"
      address: 192.168.89.2/32
      publicKey: "${secrets.wireguard.interfaces.management.public}"
      port: 13234

  - file: wireguard.jfiola-iphone.conf
    template: network-wireguard.conf
    inputs:
      privateKey: "${secrets.wireguard.devices.jfiolaIphone.users.private}"
      address: 192.168.9.2/32
      publicKey: "${secrets.wireguard.interfaces.users.public}"
      port: 13231
