[Interface]
PrivateKey = ${inputs.privateKey}
Address = ${inputs.address}
DNS = 192.168.88.1

[Peer]
PublicKey = ${inputs.publicKey}
Endpoint = wireguard.fiola.dev:${inputs.port}
AllowedIPs = 192.168.0.0/16
