[Interface]
PrivateKey = {{ inputs.privateKey }}
Address = {{ inputs.address }}
{%- if "192.168.88.1/32" in inputs.allowedIps %}
DNS = 192.168.88.1
{%- endif %}

[Peer]
PublicKey = {{ inputs.publicKey }}
Endpoint = wireguard.fiola.dev:{{ inputs.port }}
AllowedIPs = {{ inputs.allowedIps | join(", ") }}
