// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema BucketSync
 */
export class BucketSync extends ApiObject {
  /**
   * Returns the apiVersion and kind for "BucketSync"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bucket-sync.homelab-helper.benfiola.com/v1',
    kind: 'BucketSync',
  }

  /**
   * Renders a Kubernetes manifest for "BucketSync".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: BucketSyncProps): any {
    return {
      ...BucketSync.GVK,
      ...toJson_BucketSyncProps(props),
    };
  }

  /**
   * Defines a "BucketSync" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: BucketSyncProps) {
    super(scope, id, {
      ...BucketSync.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...BucketSync.GVK,
      ...toJson_BucketSyncProps(resolved),
    };
  }
}

/**
 * @schema BucketSync
 */
export interface BucketSyncProps {
  /**
   * @schema BucketSync#metadata
   */
  readonly metadata: ApiObjectMetadata;

  /**
   * @schema BucketSync#spec
   */
  readonly spec: BucketSyncSpec;
}

/**
 * Converts an object of type 'BucketSyncProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_BucketSyncProps(obj: BucketSyncProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_BucketSyncSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema BucketSyncSpec
 */
export interface BucketSyncSpec {
  /**
   * @schema BucketSyncSpec#destination
   */
  readonly destination: string;

  /**
   * @schema BucketSyncSpec#jobLabels
   */
  readonly jobLabels?: { [key: string]: string };

  /**
   * @schema BucketSyncSpec#secret
   */
  readonly secret: string;

  /**
   * @schema BucketSyncSpec#source
   */
  readonly source: string;
}

/**
 * Converts an object of type 'BucketSyncSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_BucketSyncSpec(obj: BucketSyncSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'destination': obj.destination,
    'jobLabels': ((obj.jobLabels) === undefined) ? undefined : (Object.entries(obj.jobLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'secret': obj.secret,
    'source': obj.source,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 *
 *
 * @schema BucketSyncPolicy
 */
export class BucketSyncPolicy extends ApiObject {
  /**
   * Returns the apiVersion and kind for "BucketSyncPolicy"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'bucket-sync.homelab-helper.benfiola.com/v1',
    kind: 'BucketSyncPolicy',
  }

  /**
   * Renders a Kubernetes manifest for "BucketSyncPolicy".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: BucketSyncPolicyProps): any {
    return {
      ...BucketSyncPolicy.GVK,
      ...toJson_BucketSyncPolicyProps(props),
    };
  }

  /**
   * Defines a "BucketSyncPolicy" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: BucketSyncPolicyProps) {
    super(scope, id, {
      ...BucketSyncPolicy.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...BucketSyncPolicy.GVK,
      ...toJson_BucketSyncPolicyProps(resolved),
    };
  }
}

/**
 * @schema BucketSyncPolicy
 */
export interface BucketSyncPolicyProps {
  /**
   * @schema BucketSyncPolicy#metadata
   */
  readonly metadata: ApiObjectMetadata;

  /**
   * @schema BucketSyncPolicy#spec
   */
  readonly spec: BucketSyncPolicySpec;
}

/**
 * Converts an object of type 'BucketSyncPolicyProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_BucketSyncPolicyProps(obj: BucketSyncPolicyProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_BucketSyncPolicySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema BucketSyncPolicySpec
 */
export interface BucketSyncPolicySpec {
  /**
   * @schema BucketSyncPolicySpec#destination
   */
  readonly destination: string;

  /**
   * @schema BucketSyncPolicySpec#jobLabels
   */
  readonly jobLabels?: { [key: string]: string };

  /**
   * @schema BucketSyncPolicySpec#schedule
   */
  readonly schedule: string;

  /**
   * @schema BucketSyncPolicySpec#secret
   */
  readonly secret: string;

  /**
   * @schema BucketSyncPolicySpec#source
   */
  readonly source: string;
}

/**
 * Converts an object of type 'BucketSyncPolicySpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_BucketSyncPolicySpec(obj: BucketSyncPolicySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'destination': obj.destination,
    'jobLabels': ((obj.jobLabels) === undefined) ? undefined : (Object.entries(obj.jobLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'schedule': obj.schedule,
    'secret': obj.secret,
    'source': obj.source,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

