cameras:
  doorbell_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/doorbell_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/doorbell_camera
          roles:
            - record
    review:
      alerts:
        required_zones:
          - left_front_yard
          - right_front_yard
          - walkway
      detections: {}
    zones:
      left_front_yard:
        coordinates: 0,0.476,0.269,0.48,0.346,0.538,0.478,0.556,0.495,0.568,0.51,0.59,0.505,0.617,0.47,0.679,0.47,0.736,0.482,0.806,0.484,0.923,0.422,1,0,1
        inertia: 3
        loitering_time: 0
        friendly_name: Left Front Yard
      walkway:
        coordinates: 0.476,0.556,0.508,0.58,0.513,0.598,0.473,0.678,0.474,0.739,0.486,0.801,0.488,0.925,0.426,1,1,1,1,0.003,0.849,0.005,0.675,0.344,0.676,0.363,0.873,0.398,0.858,0.787,0.728,0.691,0.726,0.712,0.625,0.663,0.575,0.622,0.575,0.601,0.58,0.575,0.55,0.555
        loitering_time: 0
        friendly_name: Walkway
        inertia: 3
      right_front_yard:
        coordinates: 0.632,0.552,0.645,0.498,0.684,0.475,0.712,0.474,0.739,0.48,0.798,0.501,0.832,0.465,0.87,0.429,0.856,0.785,0.725,0.688,0.723,0.709,0.625,0.661,0.576,0.621,0.578,0.591,0.58,0.572,0.546,0.555
        loitering_time: 0
        friendly_name: Right Front Yard
        inertia: 3
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: true
  front_yard_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_yard_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/front_yard_camera
          roles:
            - record
    review:
      alerts:
        required_zones: right_front_yard
      detections: {}
    zones:
      right_front_yard:
        coordinates: 0,0.847,0.07,0.689,0.082,0.515,0.12,0.397,0.176,0.342,0.226,0.332,0.275,0.277,0.302,0.235,0.329,0.22,0.351,0.193,0.377,0.204,0.402,0.204,0.437,0.203,0.471,0.164,0.517,0.137,0.561,0.146,0.596,0.207,0.641,0.225,0.675,0.203,0.71,0.201,0.744,0.277,0.765,0.378,0.793,0.457,0.834,0.522,0.886,0.612,0.955,0.753,1,0.872,1,1,0,1
        inertia: 3
        loitering_time: 0
        friendly_name: Right Front Yard
    motion:
      threshold: 50
      contour_area: 40
      improve_contrast: true
  garage_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/garage_camera
          roles:
            - record
    review:
      alerts:
        required_zones:
          - driveway
          - side_garden
      detections: {}
    zones:
      side_garden:
        coordinates: 0.189,1,0.325,0.246,0.371,0.08,0.167,0.266,0,0.568,0,1
        loitering_time: 0
        inertia: 3
        friendly_name: Side Garden
      driveway:
        coordinates: 0.192,1,0.327,0.246,0.372,0.087,0.386,0.318,0.602,0.242,0.791,0.568,0.836,0.169,0.894,0.254,0.926,0,1,0,1,1
        loitering_time: 0
        inertia: 3
        friendly_name: Driveway
    motion:
      threshold: 50
      contour_area: 35
      improve_contrast: true
  porch_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/porch_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/porch_camera
          roles:
            - record
    review:
      alerts:
        required_zones:
          - left_front_yard
          - right_front_yard
          - walkway
      detections: {}
    zones:
      left_front_yard:
        coordinates: 0.006,0.472,0.14,0.215,0.157,0.201,0.165,0.285,0.334,0.207,0.603,0.617,0.722,0.828,0.513,1,0,1
        loitering_time: 0
        friendly_name: Left Front Yard
        inertia: 3
      walkway:
        coordinates: 0.402,0.18,0.336,0.204,0.421,0.343,0.491,0.443,0.613,0.63,0.726,0.822,0.768,0.774,0.804,0.489,0.817,0.254,0.814,0.035,0.789,0.028,0.779,0.45,0.673,0.367,0.672,0.391,0.602,0.361,0.519,0.304,0.485,0.263,0.472,0.23,0.444,0.211
        loitering_time: 0
        friendly_name: Walkway
      right_front_yard:
        coordinates: 0.408,0.18,0.477,0.154,0.542,0.116,0.594,0.105,0.636,0.107,0.666,0.114,0.706,0.121,0.738,0.127,0.767,0.131,0.784,0.14,0.776,0.439,0.674,0.361,0.668,0.383,0.598,0.357,0.53,0.307,0.483,0.263,0.476,0.228
        loitering_time: 0
        friendly_name: Right Front Yard
        inertia: 3
    motion:
      threshold: 40
      contour_area: 25
      improve_contrast: true
detect:
  enabled: true
  stationary:
    threshold: 10
detectors:
  ov:
    type: openvino
    device: GPU
ffmpeg:
  input_args: preset-rtsp-restream
go2rtc:
  streams:
    doorbell_camera:
      - rtsp://admin:{FRIGATE_CAMERA_DOORBELL_PASSWORD}@doorbell.camera.bulia.dev:554/h265Preview_01_main
    doorbell_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_DOORBELL_PASSWORD}@doorbell.camera.bulia.dev:554/h265Preview_01_sub
    front_yard_camera:
      - rtsp://admin:{FRIGATE_CAMERA_FRONT_YARD_PASSWORD}@front-yard.camera.bulia.dev:554/Streaming/channels/101
    front_yard_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_FRONT_YARD_PASSWORD}@front-yard.camera.bulia.dev:554/Streaming/channels/102
    garage_camera:
      - rtsp://admin:{FRIGATE_CAMERA_GARAGE_PASSWORD}@garage.camera.bulia.dev:554/Streaming/channels/101
    garage_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_GARAGE_PASSWORD}@garage.camera.bulia.dev:554/Streaming/channels/102
    porch_camera:
      - rtsp://admin:{FRIGATE_CAMERA_PORCH_PASSWORD}@porch.camera.bulia.dev:554/Streaming/channels/101
    porch_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PORCH_PASSWORD}@porch.camera.bulia.dev:554/Streaming/channels/102
    candidates:
      - 10.244.0.0/16
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
mqtt:
  enabled: true
  host: mosquitto.mosquitto.svc
  port: 1883
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
objects:
  track:
    - backpack
    - bicycle
    - bird
    - bus
    - car
    - cat
    - dog
    - handbag
    - hat
    - motorcycle
    - person
    - skateboard
    - suitcase
    - umbrella
record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 1
  alerts:
    retain:
      days: 1
      mode: all
  detections:
    retain:
      days: 1
      mode: all
semantic_search:
  enabled: false
telemetry:
  stats:
    intel_gpu_stats: true
tls:
  enabled: false
version: 0.17-0
