cameras:
  doorbell_camera:
    detect:
      enabled: true
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://localhost:8554/doorbell_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/doorbell_camera
          roles:
            - record
    zones:
      left_front_yard:
        coordinates: 0,0.476,0.269,0.48,0.342,0.48,0.394,0.516,0.474,0.537,0.495,0.568,0.51,0.59,0.505,0.617,0.47,0.679,0.47,0.736,0.482,0.806,0.484,0.923,0.422,1,0,1
        inertia: 3
        loitering_time: 0
        friendly_name: Left Front Yard
      walkway:
        coordinates: 0.477,0.537,0.484,0.555,0.508,0.58,0.513,0.598,0.473,0.678,0.474,0.739,0.486,0.801,0.488,0.925,0.426,1,1,1,1,0.003,0.849,0.005,0.675,0.344,0.676,0.363,0.873,0.398,0.858,0.787,0.728,0.691,0.726,0.712,0.625,0.663,0.575,0.622,0.575,0.601,0.579,0.58,0.563,0.559,0.532,0.537
        loitering_time: 0
        friendly_name: Walkway
        inertia: 3
      right_front_yard:
        coordinates: 0.536,0.538,0.609,0.536,0.614,0.492,0.661,0.48,0.697,0.466,0.725,0.464,0.789,0.474,0.827,0.446,0.872,0.427,0.856,0.785,0.725,0.688,0.723,0.709,0.625,0.661,0.576,0.621,0.578,0.591,0.58,0.572,0.564,0.555
        loitering_time: 0
        friendly_name: Right Front Yard
        inertia: 3
  front_yard_camera:
    detect:
      enabled: true
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://localhost:8554/front_yard_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/front_yard_camera
          roles:
            - record
    zones:
      right_front_yard:
        coordinates: 0,0.825,0.065,0.689,0.054,0.526,0.101,0.386,0.166,0.32,0.211,0.307,0.267,0.259,0.297,0.202,0.322,0.188,0.336,0.118,0.37,0.118,0.403,0.175,0.431,0.167,0.438,0.092,0.516,0.101,0.57,0.114,0.586,0.171,0.63,0.189,0.662,0.189,0.704,0.144,0.761,0.241,0.767,0.346,0.796,0.373,0.841,0.443,0.89,0.526,0.971,0.667,1,0.719,1,1,0,1
        inertia: 3
        loitering_time: 0
        friendly_name: Right Front Yard
  garage_camera:
    detect:
      enabled: true
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://localhost:8554/garage_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/garage_camera
          roles:
            - record
    zones:
      side_garden:
        coordinates: 0.189,1,0.325,0.246,0.377,0.058,0.162,0.237,0,0.517,0,1
        loitering_time: 0
        inertia: 3
        friendly_name: Side Garden
      driveway:
        coordinates: 0.192,1,0.327,0.246,0.377,0.058,0.389,0.275,0.592,0.217,0.775,0.525,0.82,0.158,0.894,0.254,0.926,0,1,0,1,1
        loitering_time: 0
        inertia: 3
        friendly_name: Driveway
  porch_camera:
    detect:
      enabled: true
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://localhost:8554/porch_camera_sub
          roles:
            - detect
        - path: rtsp://localhost:8554/porch_camera
          roles:
            - record
    zones:
      left_front_yard:
        coordinates: 0.006,0.472,0.14,0.215,0.169,0.178,0.174,0.263,0.334,0.207,0.603,0.617,0.722,0.828,0.513,1,0,1
        loitering_time: 0
        friendly_name: Left Front Yard
      walkway:
        coordinates: 0.402,0.18,0.336,0.204,0.421,0.343,0.491,0.443,0.613,0.63,0.726,0.822,0.768,0.774,0.804,0.489,0.817,0.254,0.814,0.035,0.789,0.028,0.779,0.45,0.673,0.367,0.672,0.391,0.602,0.361,0.519,0.304,0.485,0.263,0.472,0.23,0.444,0.211
        loitering_time: 0
        friendly_name: Walkway
      right_front_yard:
        coordinates: 0.408,0.18,0.477,0.154,0.528,0.107,0.579,0.098,0.633,0.098,0.662,0.096,0.7,0.087,0.74,0.104,0.762,0.126,0.783,0.102,0.776,0.439,0.674,0.361,0.668,0.383,0.598,0.357,0.53,0.307,0.483,0.263,0.476,0.228
        loitering_time: 0
        friendly_name: Right Front Yard
detectors:
  ov:
    type: openvino
    device: GPU
go2rtc:
  streams:
    doorbell_camera:
      - rtsp://admin:{FRIGATE_CAMERA_DOORBELL_PASSWORD}@doorbell.camera.bulia.dev:554/h265Preview_01_main
    doorbell_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_DOORBELL_PASSWORD}@doorbell.camera.bulia.dev:554/h265Preview_01_sub
    front_yard_camera:
      - rtsp://admin:{FRIGATE_CAMERA_FRONT_YARD_PASSWORD}@front-yard.camera.bulia.dev:554/Streaming/channels/101
    front_yard_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_FRONT_YARD_PASSWORD}@front-yard.camera.bulia.dev:554/Streaming/channels/102
    garage_camera:
      - rtsp://admin:{FRIGATE_CAMERA_GARAGE_PASSWORD}@garage.camera.bulia.dev:554/Streaming/channels/101
    garage_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_GARAGE_PASSWORD}@garage.camera.bulia.dev:554/Streaming/channels/102
    porch_camera:
      - rtsp://admin:{FRIGATE_CAMERA_PORCH_PASSWORD}@porch.camera.bulia.dev:554/Streaming/channels/101
    porch_camera_sub:
      - rtsp://admin:{FRIGATE_CAMERA_PORCH_PASSWORD}@porch.camera.bulia.dev:554/Streaming/channels/102
    candidates:
      - 10.244.0.0/16
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
mqtt:
  enabled: true
  host: mosquitto.mosquitto.svc
  port: 1883
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
objects:
  track:
    - backpack
    - bicycle
    - bird
    - bus
    - car
    - cat
    - dog
    - handbag
    - hat
    - motorcycle
    - person
    - skateboard
    - suitcase
    - umbrella
record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 1
  alerts:
    retain:
      days: 1
      mode: all
  detections:
    retain:
      days: 1
      mode: all
semantic_search:
  enabled: false
telemetry:
  stats:
    intel_gpu_stats: true
tls:
  enabled: false
version: 0.17-0
