frontend:
  extra_module_url:
    - /local/lovelace-card-mod/card-mod.js
ingress:
  frigate:
    ui_mode: toolbar
    title: Cameras
    icon: mdi:cctv
    url: http://frigate.frigate.svc:5000
  preview:
    ui_mode: toolbar
    parent: frigate
    url: http://frigate.frigate.svc:5000
  music:
    ui_mode: toolbar
    title: Music
    icon: mdi:music
    url: http://music-assisant.music-assistant.svc:8095
light_group_dimmer:
  delay: 1
  groups:
    - name: living_room_dimmer_group
      entities:
        - light.living_room_entryway
        - light.living_room_floor_lamp
        - light.living_room_tracklight_1
        - light.living_room_tracklight_2
logger:
  default: info
lovelace:
  resource_mode: yaml
  dashboards:
    dashboard-thermostat:
      mode: yaml
      title: Thermostat
      icon: mdi:thermometer
      show_in_sidebar: true
      filename: dashboard-thermostat.yaml
    dashboard-lights:
      mode: yaml
      title: Lights
      icon: mdi:lightbulb-on
      show_in_sidebar: true
      filename: dashboard-lights.yaml
mobile_app: {}
zeroconf: {}
automation: !include automations.yaml
script: !include scripts.yaml
