automation:
  - id: "1"
    alias: Frigate (bfiola-iphone)
    description: ""
    use_blueprint:
      path: frigate_camera_notifications.yaml
      input:
        camera:
          - camera.doorbell_camera
          - camera.front_yard_camera
          - camera.garage_camera
          - camera.porch_camera
        notify_device: 499b68b6806d7572d381e2b55e5b1eea
        message: "{{ label }}{{ ' was' if type == 'end' else '' }} detected on
          the {{ camera_name }} camera{{' in the ' if after_zones|length}}{{ after_zones
          | join(', ') | replace('_', ' ' ) | title }}."
        tap_action: "{{base_url}}/frigate/preview?index=%2Fvod%2Fevent%2F{{id}}%2Fmaster.m3u8"
        url_1: "{{base_url}}/frigate/preview?index=%2Fvod%2Fevent%2F{{id}}%2Fmaster.m3u8"
        url_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
        zone_filter: true
        zones:
          - left_front_yard
          - walkway
          - right_front_yard
          - side_garden
          - garage
  - id: "2"
    alias: Frigate (jfiola-iphone)
    description: ""
    use_blueprint:
      path: frigate_camera_notifications.yaml
      input:
        camera:
          - camera.doorbell_camera
          - camera.front_yard_camera
          - camera.garage_camera
          - camera.porch_camera
        notify_device: d3e32179c47b335afcf177af7c80720c
        message: "{{ label }}{{ ' was' if type == 'end' else '' }} detected on
          the {{ camera_name }} camera{{' in the ' if after_zones|length}}{{ after_zones
          | join(', ') | replace('_', ' ' ) | title }}."
        tap_action: "{{base_url}}/frigate/preview?index=%2Fvod%2Fevent%2F{{id}}%2Fmaster.m3u8"
        url_1: "{{base_url}}/frigate/preview?index=%2Fvod%2Fevent%2F{{id}}%2Fmaster.m3u8"
        url_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
        zone_filter: true
        zones:
          - left_front_yard
          - walkway
          - right_front_yard
          - side_garden
          - garage
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16
ingress:
  frigate:
    ui_mode: toolbar
    title: Cameras
    icon: mdi:cctv
    url: http://frigate.frigate.svc:5000
  preview:
    ui_mode: toolbar
    parent: frigate
    url: http://frigate.frigate.svc:5000
logger:
  default: info
lovelace:
  resource_mode: yaml
  dashboards:
    dashboard-thermostat:
      mode: yaml
      title: Thermostat
      icon: mdi:thermometer
      show_in_sidebar: true
      filename: dashboard-thermostat.yaml
mobile_app: {}
zeroconf: {}
