automation: !include automations.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16
ingress:
  frigate:
    title: Cameras
    icon: mdi:cctv
    url: http://frigate.frigate.svc:5000
  preview:
    parent: preview
    url: /
logger:
  default: info
mobile_app: {}
zeroconf: {}
